### ISSUE TITLE
Hardcoded openssl path is failing to compile on Mac

### ISSUE THREAD

**Issue by ruchern** [Zilliqa/Zilliqa#10]
https://github.com/Zilliqa/Zilliqa/blob/ba2d15d75861496fb9c5814c8734af53f313a0da/build.sh#L22

Installed `openssl` from `homebrew` at time of this issue has the version at `1.0.2n` and thus the build is failing to compile.

**Comment by sidutta** [comment]
Issues related to mac are tracked under #7. Please use that thread. I think I had added the hardcoded path issue as a todo there. We won't be able to devote time to resolve those issues in the near future though. Feel free to make PRs and I could review them(I will comment on the one you have already made) or use a VM with ubuntu installed.
