### ISSUE TITLE
pow error when run on cuda gpu other than gpu 0

### ISSUE THREAD

**Issue by dtompichayut** [Zilliqa/Zilliqa#1015]
when run with gpu 0 it work correctly but when I tried on GPU 1 and 5 it is the same result, please check

$ tail -n 30 zilliqa-00001-log.txt 
[INFO   ][23946][10:51:30:153][InitMining                    ] BEGIN
[INFO   ][23946][10:51:30:153][UpdateDSBlockRand             ] BEGIN
[INFO   ][23946][10:51:30:153][Serialize                     ] BEGIN
[INFO   ][23946][10:51:30:153][Serialize                     ] END
[INFO   ][23946][10:51:30:153][UpdateDSBlockRand             ] END
[INFO   ][23946][10:51:30:153][GetStateRootHash              ] BEGIN
[INFO   ][23946][10:51:30:153][GetStateRootHash              ] END
[INFO   ][23946][10:51:30:153][CheckStateRoot                ] CheckStateRoot match
[INFO   ][23946][10:51:30:153][SetState                      ][Epoch 3100] Node State is now POW_SUBMISSION at epoch 3100
[INFO   ][23946][10:51:35:153][InitMining                    ][Epoch 3100] Starting PoW for new ds block number 32
[INFO   ][23946][10:51:35:153][StartPoW                      ] BEGIN
[INFO   ][23946][10:51:35:153][StartPoW                      ][Epoch 3100] Current dsblock is 32
[INFO   ][23946][10:51:35:154][PoWMine                       ] BEGIN
[INFO   ][26458][10:51:35:154][MineFullGPUThread             ] BEGIN
[INFO   ][26458][10:51:35:154][MineFullGPUThread             ] Difficulty : 3, miner index 0
[INFO   ][26458][10:51:38:960][MineFullGPUThread             ] END
[INFO   ][23946][10:51:38:960][PoWMine                       ] END
[INFO   ][23946][10:51:38:960][StartPoW                      ][Epoch 3100] Winning nonce   = 0x5c090d78
[INFO   ][23946][10:51:38:960][StartPoW                      ][Epoch 3100] Winning result  = 0x1273dc94d7994e512d23faf442fcf28d58827c2c772b3f082ffdbdd559b1a212
[INFO   ][23946][10:51:38:960][StartPoW                      ][Epoch 3100] Winning mixhash = 0xdc25536c67277831f4ba98e3cd28ee9ee9e390d809c70e815ef4c734b1517d54
[INFO   ][23946][10:51:38:960][SendPoWResultToDSComm         ] BEGIN
[INFO   ][23946][10:51:38:960][SetDSPoWSubmission            ] BEGIN
[INFO   ][23946][10:51:38:961][SetDSPoWSubmission            ] END
[INFO   ][23946][10:51:38:961][GetVCBlock                    ] 995
[INFO   ][23946][10:51:38:961][SendPoWResultToDSComm         ] END
[INFO   ][23946][10:51:38:961][StartPoW                      ] soln does not meet ds committee criteria. Will keep doing more pow
[INFO   ][23946][10:51:38:961][PoWMine                       ] BEGIN
[INFO   ][26466][10:51:38:961][MineFullGPUThread             ] BEGIN
[INFO   ][26466][10:51:38:961][MineFullGPUThread             ] Difficulty : 5, miner index 0
[INFO   ][26466][10:51:39: 71][MineFullGPUThread             ] END

it end at this line then zilliqa process terminated

$ cat last.log 
terminate called after throwing an instance of 'cuda_runtime_error'
  what():  CUDA error in func run_ethash_search at line 59 invalid resource handle

**Comment by ShengguangXiao** [comment]
How many CUDA cards on your PC? And what is the type?

**Comment by dtompichayut** [comment]
Hi, I am running on a rig with 6 GTX1070 8GB mem GPU but run only a node with a GPU assigned at a time  to check and found this case.

**Comment by dtompichayut** [comment]
the link show this and i cannot upload,
I am once upload a log for Han Wen to look about port forwarding issue.

----------------------------
You've already responded
You can only fill out this form once.

Try contacting the owner of the form if you think this is a mistake
----------------------------

**Comment by dtompichayut** [comment]
> @dtompichayut Can you submit the full zilliqa-00001-log.txt from here https://goo.gl/forms/y21CZrSwotvyNoKY2

Done

**Comment by dtompichayut** [comment]
For Reader Information.

###Test POW on GPU 0
coreclear@coreclear-rig1:~$ cd Desktop/Zilliqa/build/tests/POW/
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ ls -la
total 120832
drwxrwxr-x  3 coreclear coreclear      4096 ธ.ค.   4 20:05 .
drwxrwxr-x 16 coreclear coreclear      4096 ธ.ค.   4 19:56 ..
drwxrwxr-x  3 coreclear coreclear      4096 ธ.ค.   4 19:56 CMakeFiles
-rw-rw-r--  1 coreclear coreclear      1023 ธ.ค.   4 19:56 cmake_install.cmake
-rw-rw-r--  1 coreclear coreclear      9005 ธ.ค.   4 19:56 constants.xml
-rw-rw-r--  1 coreclear coreclear       379 ธ.ค.   4 19:56 CTestTestfile.cmake
-rw-rw-r--  1 coreclear coreclear      8374 ธ.ค.   4 19:56 Makefile
-rwxrwxr-x  1 coreclear coreclear 123681568 ธ.ค.   4 20:05 Test_POW
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ ./Test_POW 
Running 19 test cases...
CUDA_GPU_MINE enabled, test with CUDA GPU
CUDA_GPU_MINE enabled, test with CUDA GPU

*** No errors detected
g3log g3FileSink shutdown at: 11:45:16 848855
Log file at: [./zilliqa-00001-log.txt]


###Test POW on GPU 1
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ 
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ ./Test_POW 
Running 19 test cases...
CUDA_GPU_MINE enabled, test with CUDA GPU
terminate called after throwing an instance of 'cuda_runtime_error'
  what():  CUDA error in func run_ethash_search at line 59 invalid resource handle
unknown location(0): fatal error in "gpu_mining_and_verification_1": signal: SIGABRT (application abort requested)
/home/coreclear/Desktop/Zilliqa/tests/POW/test_POW.cpp(395): last checkpoint
CUDA_GPU_MINE enabled, test with CUDA GPU

^C


###Test POW on GPU 2
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ ./Test_POW 
Running 19 test cases...
CUDA_GPU_MINE enabled, test with CUDA GPU
terminate called after throwing an instance of 'cuda_runtime_error'
  what():  CUDA error in func run_ethash_search at line 59 invalid resource handle
unknown location(0): fatal error in "gpu_mining_and_verification_1": signal: SIGABRT (application abort requested)
/home/coreclear/Desktop/Zilliqa/tests/POW/test_POW.cpp(395): last checkpoint
CUDA_GPU_MINE enabled, test with CUDA GPU
^C

**Comment by dtompichayut** [comment]
> @dtompichayut Can you checkout branch fix/select_gpu and build zilliqa, and run this test again. Thanks very much.

Look like this solve in your fix, will try in mining test again, thank

```
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ vi constants.xml 
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ cat constants.xml | grep GPU
        <!-- Which GPU to use, can use multiple GPU, for example: "0, 2, 4" -->
        <GPU_TO_USE>0</GPU_TO_USE>
        <CUDA_GPU_MINE>true</CUDA_GPU_MINE>
        <OPENCL_GPU_MINE>false</OPENCL_GPU_MINE>
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ ./Test_POW 
Running 19 test cases...
CUDA_GPU_MINE enabled, test with CUDA GPU
CUDA_GPU_MINE enabled, test with CUDA GPU

*** No errors detected
g3log g3FileSink shutdown at: 21:57:12 350310
Log file at: [./zilliqa-00001-log.txt]
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ vi constants.xml 
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ cat constants.xml | grep GPU
        <!-- Which GPU to use, can use multiple GPU, for example: "0, 2, 4" -->
        <GPU_TO_USE>1</GPU_TO_USE>
        <CUDA_GPU_MINE>true</CUDA_GPU_MINE>
        <OPENCL_GPU_MINE>false</OPENCL_GPU_MINE>
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ ./Test_POW 
Running 19 test cases...
CUDA_GPU_MINE enabled, test with CUDA GPU
CUDA_GPU_MINE enabled, test with CUDA GPU

*** No errors detected
g3log g3FileSink shutdown at: 21:58:01 578828
Log file at: [./zilliqa-00001-log.txt]
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ 
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ 
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ vi constants.xml 
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ cat constants.xml | grep GPU
        <!-- Which GPU to use, can use multiple GPU, for example: "0, 2, 4" -->
        <GPU_TO_USE>2</GPU_TO_USE>
        <CUDA_GPU_MINE>true</CUDA_GPU_MINE>
        <OPENCL_GPU_MINE>false</OPENCL_GPU_MINE>
coreclear@coreclear-rig1:~/Desktop/Zilliqa/build/tests/POW$ ./Test_POW 
Running 19 test cases...
CUDA_GPU_MINE enabled, test with CUDA GPU
CUDA_GPU_MINE enabled, test with CUDA GPU

*** No errors detected
g3log g3FileSink shutdown at: 21:58:48 068514
Log file at: [./zilliqa-00001-log.txt]
```

**Comment by ShengguangXiao** [comment]
@dtompichayut Great, thanks for your help

**Comment by dtompichayut** [comment]
Is this normal for POW Test?
```
[INFO   ][15587][18-12-12T14:56:50.529][InitCUDA                      ] Generate dag Nvidia GPU #0
[INFO   ][15587][18-12-12T14:56:50.711][InitCUDA                      ] CUDA GPU initialized in POW
[INFO   ][15587][18-12-12T14:56:50.717][PoWMine                       ] BEGIN
[INFO   ][15597][18-12-12T14:56:50.718][MineFullGPUThread             ] BEGIN
[INFO   ][15597][18-12-12T14:56:50.718][MineFullGPUThread             ] Difficulty : 10, miner index 0
[INFO   ][15597][18-12-12T14:56:55.148][MineFullGPUThread             ] END
[INFO   ][15587][18-12-12T14:56:55.148][PoWMine                       ] END
[INFO   ][15587][18-12-12T14:56:55.148][PoWVerify                     ] BEGIN
[INFO   ][15587][18-12-12T14:56:55.155][PoWVerify                     ] END
[INFO   ][15587][18-12-12T14:56:55.155][PoWVerify                     ] BEGIN
[INFO   ][15587][18-12-12T14:56:55.155][PoWVerify                     ] END
[INFO   ][15587][18-12-12T14:56:55.155][PoWVerify                     ] BEGIN
[WARNING][15587][18-12-12T14:56:55.156][PoWVerify                     ] PoW solution doesn't meet difficulty requirement
[INFO   ][15587][18-12-12T14:56:55.156][PoWVerify                     ] END
[INFO   ][15587][18-12-12T14:56:55.156][PoWVerify                     ] BEGIN
[INFO   ][15587][18-12-12T14:56:55.156][PoWVerify                     ] END
[INFO   ][15587][18-12-12T14:56:55.158][PoWMine                       ] BEGIN
[INFO   ][15600][18-12-12T14:56:55.746][MineFullGPUThread             ] BEGIN
[INFO   ][15600][18-12-12T14:56:55.746][MineFullGPUThread             ] Difficulty : 10, miner index 0
[INFO   ][15600][18-12-12T14:57:00.365][MineFullGPUThread             ] END
[INFO   ][15587][18-12-12T14:57:00.365][PoWMine                       ] END
[INFO   ][15587][18-12-12T14:57:00.365][PoWVerify                     ] BEGIN
[INFO   ][15587][18-12-12T14:57:00.370][PoWVerify                     ] END
[INFO   ][15587][18-12-12T14:57:00.370][PoWVerify                     ] BEGIN
[INFO   ][15587][18-12-12T14:57:00.371][PoWVerify                     ] END
[INFO   ][15587][18-12-12T14:57:00.371][PoWVerify                     ] BEGIN
[WARNING][15587][18-12-12T14:57:00.371][PoWVerify                     ] PoW solution doesn't meet difficulty requirement
[INFO   ][15587][18-12-12T14:57:00.371][PoWVerify                     ] END
[INFO   ][15587][18-12-12T14:57:00.371][PoWVerify                     ] BEGIN
[INFO   ][15587][18-12-12T14:57:00.371][PoWVerify                     ] END
[INFO   ][15587][18-12-12T14:57:00.372][PoWMine                       ] BEGIN
[WARNING][15587][18-12-12T14:57:00.372][EthashConfigureClient         ] WARNING: How come the latest block number is smaller than current block number? block_number: 0 currentBlockNum: 34567
```

**Comment by ShengguangXiao** [comment]
Yes, this is to verify the POW result with a higher difficulty, then it failed, it is expected result.

**Comment by dtompichayut** [comment]
Since pow test is work, this should close
