### ISSUE TITLE
I'm getting this error

### ISSUE THREAD

**Issue by HeadOnAPike** [Zilliqa/Zilliqa#1035]
~/Downloads/Zilliqa$ ./build.sh
-- We are on a Linux system
-- Building and installing g3log
CMake Error at cmake/InstallG3log.cmake:20 (message):
  Error when building and installing g3log, see more in log
  /home/james/Downloads/Zilliqa/build/install_g3log.log
Call Stack (most recent call first):
  CMakeLists.txt:39 (include)

-- Configuring incomplete, errors occurred!
See also "/home/james/Downloads/Zilliqa/build/CMakeFiles/CMakeOutput.log".

**Comment by robin-thomas** [comment]
Can you post the logs of `/home/james/Downloads/Zilliqa/build/install_g3log.log`?

**Comment by bb111189** [comment]
Closing as this issue seems to be obsolete. Please re-open or post in our forum (https://forum.zilliqa.com/) if you are still having issue.
