### ISSUE TITLE
Elastico Implementation

### ISSUE THREAD

**Issue by ayushiagg** [Zilliqa/Zilliqa#1065]
Hi, I have been reading Elastico paper recently. I was interested in using it as a consensus protocol in some type of blockchain and trying something, but I am unable to get its implementation. Moreover, it seems to be complex to implement it in a week or so. So How can you help me with this issue?

**Comment by bb111189** [comment]
Hi. I am closing this issue as this issue tracker for Zilliqa code related issues You may wish to bring the discussion to our forum for more in-depth discussion with our community https://forum.zilliqa.com/

**Comment by ayushiagg** [comment]
@bb111189 Zilliqa's consensus is based on Elastico. That is the reason I have put up this issue.
