### ISSUE TITLE
when launch.sh    get error   in   last.log

### ISSUE THREAD

**Issue by ThomasAYuan** [Zilliqa/Zilliqa#1110]
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::ptree_bad_path> >'
  what():  No such node (node.constants.MSG_VERSION)

**Comment by ShengguangXiao** [comment]
Please check if the constants.xml is with the zilliqa executable file
