### ISSUE TITLE
error - build.sh

### ISSUE THREAD

**Issue by EduardoRosendo** [Zilliqa/Zilliqa#1142]
Scanning dependencies of target Lookup
[ 85%] Building CXX object src/libLookup/CMakeFiles/Lookup.dir/Lookup.cpp.o
[ 85%] Building CXX object src/libLookup/CMakeFiles/Lookup.dir/Synchronizer.cpp.o
/home/er/Zilliqa/src/libLookup/Lookup.cpp: In member function ‘void Lookup::SendTxnPacketToNodes(uint32_t)’:
/home/er/Zilliqa/src/libLookup/Lookup.cpp:3268:69: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
           if (distance(m_mediator.m_ds->m_shards.at(i).begin(), it) ==
                                                                                                         ^
cc1plus: all warnings being treated as errors
src/libLookup/CMakeFiles/Lookup.dir/build.make:62: recipe for target 'src/libLookup/CMakeFiles/Lookup.dir/Lookup.cpp.o' failed
make[2]: *** [src/libLookup/CMakeFiles/Lookup.dir/Lookup.cpp.o] Error 1
CMakeFiles/Makefile2:1479: recipe for target 'src/libLookup/CMakeFiles/Lookup.dir/all' failed
make[1]: *** [src/libLookup/CMakeFiles/Lookup.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
er@er-P5GZ-MX:~/Zilliqa$

**Comment by evesnow91** [comment]
Please pull the latest master and build.
