### ISSUE TITLE
GPU/CPU mining on Windows 10

### ISSUE THREAD

**Issue by whalehub** [Zilliqa/Zilliqa#1143]
As far as you know, is it currently possible to mine on the Zilliqa testnet with your GPU/CPU on a Windows 10 computer by virtualizing the required Ubuntu Xenial host?

If so, do you need to use a specific virtualization software that supports GPU/CPU passthrough or something of the sort? Or is it perhaps possible to do it by using Docker for Windows or the Windows Subsystem for Linux?

If not, you should seriously consider looking into this topic because the overwhelming majority of home users, i.e. Zilliqa's target audience, aren't running Linux on their PCs and even most people with a Linux home server don't have an Nvidia GPU in them.

This leads to the problem that only very few people are able to perform GPU/CPU mining on the Zilliqa testnet in spite of the fact that most people, especially those interested in crypto, already have either a powerful CPU or an Nvidia GPU or even both in their computer.

**Comment by bb111189** [comment]
You may want to take a look at zilminer developed by one of our community members, deepgully. https://forum.zilliqa.com/t/zilminer-beta-released/229
