### ISSUE TITLE
A question about Zilliqa Paper(A Secure Sharding Protocol)

### ISSUE THREAD

**Issue by spritehigh** [Zilliqa/Zilliqa#1185]
Recently,I am reading <<A secure Sharding Protocol for Open BlockChains>>,this paper is well,but there has some question:
In this paper,"ELaSTICO tolerates up to f<n/4 adaptive byzantine adversaries",but to my knowledge,the bound is 1/3,and if malicious nodes up to nearly 1/3, in that formula:
[https://imgchr.com/i/Fjs5Sf](url),when f=1/4,the Pr[X,=2n'/3] is about 0.0389I want to know ,why team choose f=0.25,rather than choose other number,like f=0.3 or bigger?I think f=0.25 is unsafe

**Comment by evesnow91** [comment]
Non code-related issues. Please use the [forum](https://forum.zilliqa.com/) for such queries.
