### ISSUE TITLE
Transaction should fail when contract invokes another contract with empty `_tag`

### ISSUE THREAD

**Issue by vaivaswatha** [Zilliqa/Zilliqa#1270]
It looks like this piece of code 

```
  // Recipient is contract
  // _tag field is empty
  if (_json["message"]["_tag"].asString().empty()) {
    LOG_GENERAL(INFO,
                "_tag in the scilla output is empty when invoking a "
                "contract, transaction finished");
    return true;
  }
```

In AccountStoreSC.cpp must `return false` (and no balance transfer must happen). This can otherwise lead to the case where the interpreter will have subtracted the `_amount` from the contract's balance, but it doesn't get credited to the recipient (because `_tag` is empty, the recipient contract cannot "accept" the money). 

In such a case, `return false` (and ignoring any balance transfer) will ensure that the output of the interpreter (except for gas charged) is ignored and the transaction doesn't go through.

**Comment by kaikawaliu** [comment]
Actually the contract's balance will only be deducted when another invocation was triggered, so far at this lines of code the transfer wasn't happened yet.
If we choose to return false, then the only way to successfully return an execution is having a non-contract recipient, but that's difficult as every contract need to make sure they are having some non-contract as a default final recipient.
Instead, the contract can terminate itself by setting the recipient to be the address of himself, and ended with putting empty `_tag`

**Comment by vaivaswatha** [comment]
Thank you @kaikawaliu . Closing as "not an Issue"
