### ISSUE TITLE
Add initial .gitattributes

### ISSUE THREAD

**Issue by sharwell** [Zilliqa/Zilliqa#13]
I'm working on adding an initial **.gitattributes** file. It's generally straightforward¹, but I have a few questions:

1. Was the file [src/depends/Makefile](https://github.com/Zilliqa/Zilliqa/blob/21cb318b0923b7714088729e084bd48a5033ffa6/src/depends/Makefile) intended to be removed as part of 2c459abe314b5f40658121a72c07741baeefee45? I see that the file is excluded per **.gitignore** starting in bb9e4e6571f511bcdf186892e6f0906e465f5091, but I wanted to verify before submitting a pull request to remove all these files.
2. While scripts should have permissions 100755 in Git, I see that other files like [CMakeLists.txt](https://github.com/Zilliqa/Zilliqa/blob/21cb318b0923b7714088729e084bd48a5033ffa6/CMakeLists.txt) and [tests/Data/Test_Block.cpp](https://github.com/Zilliqa/Zilliqa/blob/21cb318b0923b7714088729e084bd48a5033ffa6/tests/Data/Test_Block.cpp) are also added like this. Is it a problem to submit a pull request that changes these files from 100755&rarr;100644?
  

¹ I always make sure **.gitattributes** and **.gitignore** are consistent during this change, since it can otherwise lead to weird merge conflicts down the road. It's much easier to get it sorted out up front, hence the questions before sending the PR. :smile:

**Comment by sidutta** [comment]
1. Removing the Makefiles was intentional. We just want the CMakeLists.txt to remain in the repo.
2. 644 is the way to go. A PR would be welcome. Thanks!

Closing it, feel free to reopen if needed.

**Comment by ruchern** [comment]
@sidutta How did you managed to close the issue for not being a collaborator of this repo?

**Comment by sharwell** [comment]
:bulb: @sidutta This issue is intended to be closed with #14, which is not yet merged. My use of the text `Closes #13` in the description of pull request #14 will cause GitHub to automatically close this issue when the pull request is merged.

**Comment by sidutta** [comment]
Oh. Due to "I wanted to verify before submitting a pull request", "up front", "questions before sending the PR", I felt the answers to the questions should close the issue rather than merging of the PRs. I am not sure how changes in #14 are related to the contents of this issue. Relevant actions on #15 and #16 were taken. 

I know closes :)
