### ISSUE TITLE
Potential divided-by-zero

### ISSUE THREAD

**Issue by Gnnng** [Zilliqa/Zilliqa#130]
If `numOfComms` ever becomes 0, there would be a divided-by-zero crash in the following locations.

https://github.com/Zilliqa/Zilliqa/blob/f00345d30d98a3e62177cfb7a74ca9598061138c/src/libDirectoryService/ShardingPreProcessing.cpp#L78-L80

`numOfComms` is defined here at https://github.com/Zilliqa/Zilliqa/blob/f00345d30d98a3e62177cfb7a74ca9598061138c/src/libDirectoryService/ShardingPreProcessing.cpp#L48

It's not clear whether m_allPoW2s.size() is guaranteed to be non-zero before this function is called. Maybe it's better to put some check here.

**Comment by bb111189** [comment]
We need to think on how to handle the situation when nodes fall below the COMM_SIZE. For now, I will throw a exception and log it down. 

@jiayaoqijia

**Comment by bb111189** [comment]
My opinion is that operating below the min comm_size is not secure. We will need to restart process of pow1 and pow2 rather than moving forward.

**Comment by bb111189** [comment]
I am thinking in such a case, I will restart pow2 phase.
