### ISSUE TITLE
Some doubts about node

### ISSUE THREAD

**Issue by Gsuslu** [Zilliqa/Zilliqa#1328]
Hi, 

yesterday finallly i got this working. I have create a proxy server but have some doubts if its working correctly. 

I put some screenshots

![image](https://user-images.githubusercontent.com/47099454/51819257-0f7f7a80-22d2-11e9-8eb5-2279f28c5eea.png)

![image](https://user-images.githubusercontent.com/47099454/51819309-3ccc2880-22d2-11e9-9cfe-d7af4277413b.png)

Like you can see in the second screenshot i have this message many time:

[Epoch 5240] ProcessSetTxBlockFromSeed sent by <34.217.21.132:17519> for blocks 5240 to 5239
[WARN][  516][19-01-28T06:56:57.907][okup/Lookup.cpp:1744][ProcessSetTxBlockFromSeed] The lowBlockNum is higher the highblocknum, maybe DS epoch ongoing

Any ideas?

Thanks

**Comment by bb111189** [comment]
```
[Epoch 5240] ProcessSetTxBlockFromSeed sent by <34.217.21.132:17519> for blocks 5240 to 5239
[WARN][ 516][19-01-28T06:56:57.907][okup/Lookup.cpp:1744][ProcessSetTxBlockFromSeed] The lowBlockNum is higher the highblocknum, maybe DS epoch ongoing
```

This message should be fine. Are you having any issue?

**Comment by Gsuslu** [comment]
Thanks for the answer. I think now its working... 

I have one more doubt ... im receiving sometimes this message as well:

![image](https://user-images.githubusercontent.com/47099454/51898515-57c19a00-23b1-11e9-961e-a8ef2b8eafd2.png)

I dont know if it should be ok or not...

**Comment by bb111189** [comment]
If this happens at the start of the log, it is fine.

**Comment by Gsuslu** [comment]
Thanks man.
