### ISSUE TITLE
Improve the less-than operator overloading with std::tie

### ISSUE THREAD

**Issue by Gnnng** [Zilliqa/Zilliqa#133]
Most of the block classes (e.g., `MicroBlock`, `TxBlock`) have overloaded operator `<` and `>`, the current writing is a bit verbose. See the following example. 

https://github.com/Zilliqa/Zilliqa/blob/3ed58e2d144ab1c3b373a78be0bd141226d59b25/src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp#L206

For operator `<`, a clearer way is to use [`std::tie`](http://en.cppreference.com/w/cpp/utility/tuple/tie).

```
    bool operator<(const S& rhs) const
    {
        // compares n to rhs.n,
        // then s to rhs.s,
        // then d to rhs.d
        return std::tie(n, s, d) < std::tie(rhs.n, rhs.s, rhs.d);
    }
```

For operator `>`, it's better to be defined in terms of `<`. See the [suggestion](http://en.cppreference.com/w/cpp/language/operators).

```
inline bool operator< (const X& lhs, const X& rhs){ /* do actual comparison */ }
inline bool operator> (const X& lhs, const X& rhs){ return rhs < lhs; }
```

**Comment by ansnunez** [comment]
This has now been implemented in libData
