### ISSUE TITLE
Running test_node_lookup_local.sh saying API Server couldn't start

### ISSUE THREAD

**Issue by kaikawaliu** [Zilliqa/Zilliqa#134]
[zilliqa-00001-log.txt](https://github.com/Zilliqa/Zilliqa/files/1832193/zilliqa-00001-log.txt)

**Comment by kaikawaliu** [comment]
[TID 24251][06:01:39   ][Deserialize         ] BEGIN
[TID 24251][06:01:39   ][Deserialize         ] END
[TID 24251][06:01:39   ][PeerManager         ] BEGIN
[TID 24251][06:01:39   ][PeerManager         ] END
[TID 24251][06:01:39   ][Deserialize         ] BEGIN
[TID 24251][06:01:39   ][Deserialize         ] END
[TID 24251][06:01:39   ][Serialize           ] BEGIN
[TID 24251][06:01:39   ][Serialize           ] BEGIN
[TID 24251][06:01:39   ][Serialize           ] END
[TID 24251][06:01:39   ][Serialize           ] END
[TID 24251][06:01:39   ][Deserialize         ] BEGIN
[TID 24251][06:01:39   ][Deserialize         ] END
[TID 24251][06:01:39   ][Serialize           ] BEGIN
[TID 24251][06:01:39   ][Serialize           ] END
[TID 24251][06:01:39   ][UpdateDSBlockRand   ] BEGIN
[TID 24251][06:01:39   ][UpdateDSBlockRand   ] Genesis DSBlockchain
[TID 24251][06:01:39   ][UpdateDSBlockRand   ] END
[TID 24251][06:01:39   ][UpdateTxBlockRand   ] BEGIN
[TID 24251][06:01:39   ][UpdateTxBlockRand   ] Genesis txBlockchain
[TID 24251][06:01:39   ][UpdateTxBlockRand   ] END
[TID 24251][06:01:39   ][SetState            ][Epoch 1] Node State is now 0 at epoch 1
[TID 24251][06:01:42   ][Zilliqa             ] BEGIN
[TID 24251][06:01:42   ][Serialize           ] BEGIN
[TID 24251][06:01:42   ][Serialize           ] END
[TID 24251][06:01:42   ][LogSelfNodeInfo     ] Private Key (Len=32): B8B29263EF0620C3ACCB1642EA6431C6A8FAA635B7BA925C811026D4B743CE32
[TID 24251][06:01:42   ][LogSelfNodeInfo     ] Public Key (Len=33): 02DAC8A002768AB1F5F1C8135C8673037CC4A1DE40990C8C7D716F6B281DE4EB20
[TID 24251][06:01:42   ][LogSelfNodeInfo     ] My address is 63743ba4f0be9a614948657148cec465c861f409 and port is 4001
[TID 24251][06:01:42   ][Zilliqa             ] I am a lookup node.
[TID 24251][06:01:42   ][Zilliqa             ] 2. API Server couldn't start
[TID 24251][06:01:42   ][Zilliqa             ] END
[TID 24251][06:01:42   ][StartMessagePump    ] BEGIN

**Comment by kaikawaliu** [comment]
PID/Program name
tcp        0      0 0.0.0.0:4201            0.0.0.0:*               LISTEN      24255/lzilliqa  
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:4000            0.0.0.0:*               LISTEN      24249/lzilliqa  
tcp        0      0 0.0.0.0:4001            0.0.0.0:*               LISTEN      24251/lzilliqa  
tcp        0      0 0.0.0.0:4002            0.0.0.0:*               LISTEN      24253/lzilliqa  
tcp        0      0 0.0.0.0:4003            0.0.0.0:*               LISTEN      24255/lzilliqa  
tcp        0      0 0.0.0.0:4004            0.0.0.0:*               LISTEN      24257/lzilliqa  
tcp        1      0 172.17.1.112:34944      14.17.43.34:443         CLOSE_WAIT  20098/electronic-we
tcp        0      0 172.17.1.112:33758      74.125.68.188:5228      ESTABLISHED 22405/chrome    
tcp        1      0 172.17.1.112:41536      45.55.41.223:80         CLOSE_WAIT  3832/plugin_host
tcp        0      0 172.17.1.112:38092      34.207.165.252:443      ESTABLISHED 22405/chrome    
tcp        0      0 172.17.1.112:58312      183.61.49.150:443       ESTABLISHED 20098/electronic-we
tcp        0      0 172.17.1.112:50054      192.30.253.125:443      ESTABLISHED 22405/chrome    
tcp6       0      0 ::1:631                 :::*                    LISTEN      -

**Comment by bb111189** [comment]
The reason is libServer is listening on 1 port. When running locally, 5 instances of lookup-node is trying to listen on 1 port. That's why API Server couldn't start. 

@KaustubhShamshery  Can you take a look at using different port for libServer for local testing?
