### ISSUE TITLE
My node issue

### ISSUE THREAD

**Issue by Swaggadan** [Zilliqa/Zilliqa#1352]
I followed the guide , multiple times but still nothing. I made a proxy node and have my PC mine it.  I can connect to the node easily but I am not seeing or getting test blocks. I have been looking at other posts and I've even tested on other nodes and I get data. It’s on the DMZ so there is no ports to forward. I tried both WAN and LAN IP, same issue. Miner just shows.
http://prntscr.com/mdttmh

What Am I doing incorrectly?

**Comment by evesnow91** [comment]
This is an issue for: https://github.com/DurianStallSingapore/ZILMiner
