### ISSUE TITLE
Mainnet_config

### ISSUE THREAD

**Issue by SilentSeir** [Zilliqa/Zilliqa#1374]
tail -f zilliqa-00001-log.txt
	stack dump [6]  zilliqa() [0x762101]
	stack dump [7]  zilliqa() [0x4c87da]
	stack dump [8]  /usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8c80 [0x7f9dd5435c80]
	stack dump [9]  /lib/x86_64-linux-gnu/libpthread.so.0+0x76ba [0x7f9dd4c486ba]
	stack dump [10]  /lib/x86_64-linux-gnu/libc.so.6clone+0x6d [0x7f9dd497e41d]

Exiting after fatal event  (FATAL). Fatal type:  SIGABRT
Log content flushed sucessfully to sink

"g3log g3FileSink shutdown at: 16:20:56 694301

**Comment by bb111189** [comment]
Is it possible for you to provide us the full log?

**Comment by SilentSeir** [comment]
~/Desktop/join$ tail -f zilliqa-00001-log.txt 
[INFO][ 1813][19-02-02T16:57:54.797][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-02T16:57:54.797][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-02T16:57:54.797][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-02T16:57:54.882][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-02T16:57:54.943][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-02T16:57:55.932][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-02T16:57:56.018][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-02T16:57:56.095][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-02T16:57:56.095][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-02T16:57:56.095][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-02T16:58:41.095][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][ 1813][19-02-02T16:58:41.095][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1813][19-02-02T16:58:41.095][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1813][19-02-02T16:58:41.102][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-02T16:58:41.102][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-02T16:58:41.102][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-02T16:58:41.102][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-02T16:58:41.102][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-02T16:58:41.102][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-02T16:58:41.103][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-02T16:58:41.104][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-02T16:58:41.104][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-02T16:58:41.105][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-02T16:58:41.105][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-02T16:58:41.105][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-02T16:58:41.105][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-02T16:59:26.105][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][ 1813][19-02-02T16:59:26.105][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1813][19-02-02T16:59:26.105][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1813][19-02-02T16:59:26.112][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-02T16:59:26.112][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-02T16:59:26.112][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-02T16:59:26.112][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-02T16:59:26.112][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-02T16:59:26.112][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-02T16:59:26.167][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-02T16:59:26.246][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-02T16:59:26.332][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-02T16:59:26.419][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-02T16:59:26.480][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-02T16:59:26.480][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-02T16:59:26.480][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-02T17:00:11.480][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][ 1813][19-02-02T17:00:11.480][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][ 1813][19-02-02T17:00:11.481][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

**Comment by bb111189** [comment]
Hi possible to upload the full log to https://goo.gl/forms/F1swoGTFv9gqwBjI2 and we will check it out

**Comment by SilentSeir** [comment]
Alternate: 

:~/Desktop/join$ tail -f zilliqa-00001-log.txt
[INFO][ 6025][19-02-02T18:36:43.157][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.209.120.68:54410
[INFO][ 6025][19-02-02T18:36:43.157][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 54.188.254.184:54410
[INFO][ 6025][19-02-02T18:36:43.157][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.221.152.140:54410
[INFO][ 6025][19-02-02T18:36:43.157][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 35.167.171.85:54410
[INFO][ 6025][19-02-02T18:36:43.157][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.217.85.44:54410
[INFO][ 6025][19-02-02T18:36:43.157][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 52.12.104.32:54410
[INFO][ 6025][19-02-02T18:36:43.157][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 18.236.62.213:54410
[INFO][ 6025][19-02-02T18:36:43.157][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.222.34.216:54410
[INFO][ 6025][19-02-02T18:36:43.157][SendMessageToLookupNodesSerial] END
[INFO][ 6025][19-02-02T18:36:43.157][GetOfflineLookupNodes         ] END
[WARN][ 6025][19-02-02T18:37:28.157][GetOfflineLookups             ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][ 6025][19-02-02T18:37:28.158][GetOfflineLookupNodes         ] BEGIN
[INFO][ 6025][19-02-02T18:37:28.158][SetLookupNodes                ] BEGIN
[WARN][ 6025][19-02-02T18:37:28.166][Deserialize                   ] Deserialization failure
[WARN][ 6025][19-02-02T18:37:28.166][PubKey                        ] We failed to init PubKey.
[WARN][ 6025][19-02-02T18:37:28.166][PubKey                        ] src (ec point) is null in pub key construct.
[WARN][ 6025][19-02-02T18:37:28.166][PubKey                        ] src (ec point) is null in pub key construct.
[INFO][ 6025][19-02-02T18:37:28.167][SetLookupNodes                ] END
[INFO][ 6025][19-02-02T18:37:28.167][ComposeGetOfflineLookupNodes  ] BEGIN
[INFO][ 6025][19-02-02T18:37:28.167][SetLookupGetOfflineLookups    ] BEGIN
[INFO][ 6025][19-02-02T18:37:28.167][SetLookupGetOfflineLookups    ] END
[INFO][ 6025][19-02-02T18:37:28.167][ComposeGetOfflineLookupNodes  ] END
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial] BEGIN
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 50.112.30.228:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 54.185.174.51:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.209.120.68:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 54.188.254.184:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.221.152.140:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 35.167.171.85:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.217.85.44:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 52.12.104.32:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 18.236.62.213:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.222.34.216:54410
[INFO][ 6025][19-02-02T18:37:28.167][SendMessageToLookupNodesSerial] END
[INFO][ 6025][19-02-02T18:37:28.167][GetOfflineLookupNodes         ] END
[WARN][ 6025][19-02-02T18:38:13.167][GetOfflineLookups             ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][ 6025][19-02-02T18:38:13.167][GetOfflineLookupNodes         ] BEGIN
[INFO][ 6025][19-02-02T18:38:13.167][SetLookupNodes                ] BEGIN
[WARN][ 6025][19-02-02T18:38:13.176][Deserialize                   ] Deserialization failure
[WARN][ 6025][19-02-02T18:38:13.176][PubKey                        ] We failed to init PubKey.
[WARN][ 6025][19-02-02T18:38:13.176][PubKey                        ] src (ec point) is null in pub key construct.
[WARN][ 6025][19-02-02T18:38:13.176][PubKey                        ] src (ec point) is null in pub key construct.
[INFO][ 6025][19-02-02T18:38:13.177][SetLookupNodes                ] END
[INFO][ 6025][19-02-02T18:38:13.177][ComposeGetOfflineLookupNodes  ] BEGIN
[INFO][ 6025][19-02-02T18:38:13.177][SetLookupGetOfflineLookups    ] BEGIN
[INFO][ 6025][19-02-02T18:38:13.177][SetLookupGetOfflineLookups    ] END
[INFO][ 6025][19-02-02T18:38:13.177][ComposeGetOfflineLookupNodes  ] END
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial] BEGIN
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 50.112.30.228:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 54.185.174.51:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.209.120.68:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 54.188.254.184:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.221.152.140:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 35.167.171.85:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.217.85.44:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 52.12.104.32:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 18.236.62.213:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial][Epoch 1] Sending msg to lookup node 34.222.34.216:54410
[INFO][ 6025][19-02-02T18:38:13.177][SendMessageToLookupNodesSerial] END
[INFO][ 6025][19-02-02T18:38:13.177][GetOfflineLookupNodes         ] END

**Comment by SilentSeir** [comment]
/Zilliqa-Mainnetv4.0.1$ sudo ./build.sh 
-- We are on a Linux system
-- Building and installing g3log
CMake Error at cmake/InstallG3log.cmake:21 (message):
  Error when building and installing g3log, see more in log
  /TheNether/Zilliqa-Mainnetv4.0.1/build/install_g3log.log
Call Stack (most recent call first):
  CMakeLists.txt:43 (include)


-- Configuring incomplete, errors occurred!
See also "/TheNether/Zilliqa-Mainnetv4.0.1/build/CMakeFiles/CMakeOutput.log".
See also "/TheNether/Zilliqa-Mainnetv4.0.1/build/CMakeFiles/CMakeError.log".

**Comment by SilentSeir** [comment]
[INFO][ 3937][19-02-03T18:41:20.595][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 3937][19-02-03T18:41:20.595][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 3937][19-02-03T18:41:20.677][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 3937][19-02-03T18:41:20.677][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 3937][19-02-03T18:41:20.729][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 3937][19-02-03T18:41:20.729][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 3937][19-02-03T18:41:20.729][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 3937][19-02-03T18:42:05.729][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][ 3937][19-02-03T18:42:05.729][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][ 3937][19-02-03T18:42:05.729][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

**Comment by SilentSeir** [comment]
~/Desktop/join$ tail -f zilliqa-00001-log.txt 
[INFO][ 1812][19-02-04T17:56:44.045][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1812][19-02-04T17:56:44.045][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1812][19-02-04T17:56:44.045][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1812][19-02-04T17:56:44.125][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1812][19-02-04T17:56:44.187][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1812][19-02-04T17:56:44.281][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1812][19-02-04T17:56:44.365][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1812][19-02-04T17:56:44.468][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1812][19-02-04T17:56:44.468][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1812][19-02-04T17:56:44.468][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1812][19-02-04T17:57:29.468][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][ 1812][19-02-04T17:57:29.468][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1812][19-02-04T17:57:29.468][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1812][19-02-04T17:57:29.471][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1812][19-02-04T17:57:29.471][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1812][19-02-04T17:57:29.471][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1812][19-02-04T17:57:29.471][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1812][19-02-04T17:57:29.471][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1812][19-02-04T17:57:29.471][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1812][19-02-04T17:57:29.471][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1812][19-02-04T17:57:29.554][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1812][19-02-04T17:57:29.554][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1812][19-02-04T17:57:29.555][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1812][19-02-04T17:57:29.628][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1812][19-02-04T17:57:29.628][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1812][19-02-04T17:57:29.628][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1812][19-02-04T17:58:14.628][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][ 1812][19-02-04T17:58:14.628][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1812][19-02-04T17:58:14.628][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1812][19-02-04T17:58:14.631][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1812][19-02-04T17:58:14.631][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1812][19-02-04T17:58:14.631][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1812][19-02-04T17:58:14.631][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1812][19-02-04T17:58:14.631][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1812][19-02-04T17:58:14.631][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1812][19-02-04T17:58:14.683][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1812][19-02-04T17:58:14.683][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1812][19-02-04T17:58:14.758][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1812][19-02-04T17:58:14.832][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1812][19-02-04T17:58:14.833][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1812][19-02-04T17:58:14.833][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1812][19-02-04T17:58:14.833][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1812][19-02-04T17:58:59.833][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][ 1812][19-02-04T17:58:59.833][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][ 1812][19-02-04T17:58:59.833][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

**Comment by SilentSeir** [comment]
[WARN][ 4468][19-02-04T19:06:54.443][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

**Comment by bmatthewshea** [comment]
You are probably blacklisted - it seems overzealous.
I was for over a day. Then it started working.

Also please use `CODE tags for your log` so people can read it without headache.
or post it to a free site somewhere like here:
 https://hastebin.com/vuwojahane.md

Keeps thread easier to read through.

**Comment by SilentSeir** [comment]
Stuck. 

:~/Desktop/join$ tail -f zilliqa-00001-log.txt
	stack dump [6]  zilliqa() [0x762101]
	stack dump [7]  zilliqa() [0x4c87da]
	stack dump [8]  /usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8c80 [0x7efd73b2bc80]
	stack dump [9]  /lib/x86_64-linux-gnu/libpthread.so.0+0x76ba [0x7efd7333e6ba]
	stack dump [10]  /lib/x86_64-linux-gnu/libc.so.6clone+0x6d [0x7efd7307441d]

Exiting after fatal event  (FATAL). Fatal type:  SIGABRT
Log content flushed sucessfully to sink

"g3log g3FileSink shutdown at: 00:56:55 765634

?
