### ISSUE TITLE
Fix and enable multi-thread ethash POW in CPU-only node mode

### ISSUE THREAD

**Issue by Bambarello** [Zilliqa/Zilliqa#1376]
It was revealed, that when node in CPU-only POW mode, the libPOW is not activating ethash mining algorithm on all available CPU threads, only 1 thread is used (!!!).

Please fix this asap:

[GitHub link to the source](https://github.com/Zilliqa/Zilliqa/tree/master/src/libPOW)

**Comment by ningfeiguang** [comment]
Now the shard difficulty is 31 already, even developed multi threaded cpu mining, CPU still cannot finish PoW in one minutes, so no meanning to do this change

**Comment by ShengguangXiao** [comment]
Now difficulty is 31 already, even developed multi threaded cpu mining,  CPU still cannot finish PoW in one minute, so no meaning to do this fix any more

**Comment by ShengguangXiao** [comment]
@Bambarello Please try to use GPU to join the mainnet

**Comment by Bambarello** [comment]
Hello, this is not the resolution, just the excuse as the team not proprely switched-on the multithread ethash library from the very begining. This should have allowed powerful CPU nodes to be competitive during bootstrap period. 

Please advise on the plans to enable multi-threading for CPU.
