### ISSUE TITLE
	FATAL [pow.cpp->InitCUDA:783]

### ISSUE THREAD

**Issue by clawmvp** [Zilliqa/Zilliqa#1379]
trying to run docker with --cuda flag.
following this guide: Mining with docker locally (For CPU or Nvidia GPUs only)
https://github.com/Zilliqa/Zilliqa/wiki/Mining#mining-with-docker-locally-for-cpu-or-nvidia-gpus-only
system info: 1x 1080ti, i5 procesor, 16gb ram, 16.04.1-Ubuntu

docker throws this error:

*******	 EXIT trigger caused by LOG(FATAL) entry: 
	"[ 1810][19-02-03T22:39:26.159][c/libPOW/pow.cpp:783][InitCUDA            ] The software is not build with CUDA. Please enable the CUDA build option and build software again
*******	STACKDUMP *******
	stack dump [1]  zilliqa() [0xcdca9b]
	stack dump [2]  zilliqa() [0x8afa52]
	stack dump [3]  zilliqa() [0x8b0348]
	stack dump [4]  zilliqa() [0x8b05ba]
	stack dump [5]  zilliqa() [0x761dd4]
	stack dump [6]  zilliqa() [0x762101]
	stack dump [7]  zilliqa() [0x4c87da]
	stack dump [8]  /usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8c80 [0x7f508f3f3c80]
	stack dump [9]  /lib/x86_64-linux-gnu/libpthread.so.0+0x76ba [0x7f508ec066ba]
	stack dump [10]  /lib/x86_64-linux-gnu/libc.so.6clone+0x6d [0x7f508e93c41d]

Exiting after fatal event  (FATAL). Fatal type:  SIGABRT
Log content flushed sucessfully to sink

"g3log g3FileSink shutdown at: 22:39:26 159581
Log file at: [./zilliqa-00001-log.txt]

exitWithDefaultSignalHandler:229. Exiting due to FATAL, 6   

![screen shot 2019-02-04 at 6 10 30 pm](https://user-images.githubusercontent.com/28742900/52220753-480dee00-28a8-11e9-9696-5d2a15c92541.png)
![screen shot 2019-02-04 at 6 13 07 pm](https://user-images.githubusercontent.com/28742900/52221020-e7cb7c00-28a8-11e9-90b7-a95f534aca7c.png)
![screen shot 2019-02-04 at 6 13 46 pm](https://user-images.githubusercontent.com/28742900/52221023-e8641280-28a8-11e9-8e38-48c5a17e3be8.png)

**Comment by SilentSeir** [comment]
Nearly Identical Issue.

**Comment by SilentSeir** [comment]
:~/Desktop/join$ tail -f zilliqa-00001-log.txt 
	stack dump [6]  zilliqa() [0x762101]
	stack dump [7]  zilliqa() [0x4c87da]
	stack dump [8]  /usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8c80 [0x7fb215b39c80]
	stack dump [9]  /lib/x86_64-linux-gnu/libpthread.so.0+0x76ba [0x7fb21534c6ba]
	stack dump [10]  /lib/x86_64-linux-gnu/libc.so.6clone+0x6d [0x7fb21508241d]

Exiting after fatal event  (FATAL). Fatal type:  SIGABRT
Log content flushed sucessfully to sink

"g3log g3FileSink shutdown at: 20:44:40 141383

**Comment by evesnow91** [comment]
Hi all,

The CUDA docker image will be built by the end of today (GMT +8). Please download the latest CUDA image tomorrow by doing `sudo docker pull zilliqa/zilliqa:v4.0.1-cuda`.
