### ISSUE TITLE
How to start lookup node?

### ISSUE THREAD

**Issue by wangjunasd** [Zilliqa/Zilliqa#1380]
By setting LOOKUP_NODE_MODE in the constants.xml file to true, and specifying synctype to 4 or 6, after startup, it always prompts “xxx is not in my lookup node list”. If I remove the corresponding detection code and recompile, I can synchronize and get the data, but it can't be persistent. After a while, I will get an error “[work/P2PComm.cpp:491][EventCallback ] Error from bufferevent”. I want to know: What is wrong? How to open the normal lookup node, I see the official api server is in good condition.

**Comment by bb111189** [comment]
Joining of lookup node is not supported.
