### ISSUE TITLE
Cannot rejoin

### ISSUE THREAD

**Issue by SilentSeir** [Zilliqa/Zilliqa#1382]
Output from my most recent attempt: 

 tail -f zilliqa-00001-log.txt 
[INFO][16210][19-02-05T20:57:42.343][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][16210][19-02-05T20:57:42.343][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][16210][19-02-05T20:57:42.343][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][16210][19-02-05T20:57:42.420][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][16210][19-02-05T20:57:42.466][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][16210][19-02-05T20:57:42.531][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][16210][19-02-05T20:57:42.583][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][16210][19-02-05T20:57:42.648][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][16210][19-02-05T20:57:42.648][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][16210][19-02-05T20:57:42.648][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][16210][19-02-05T20:58:27.648][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][16210][19-02-05T20:58:27.648][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][16210][19-02-05T20:58:27.648][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][16210][19-02-05T20:58:27.655][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][16210][19-02-05T20:58:27.655][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][16210][19-02-05T20:58:27.655][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][16210][19-02-05T20:58:27.655][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][16210][19-02-05T20:58:27.655][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][16210][19-02-05T20:58:27.655][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][16210][19-02-05T20:58:27.656][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][16210][19-02-05T20:58:27.712][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][16210][19-02-05T20:58:27.712][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][16210][19-02-05T20:58:27.712][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][16210][19-02-05T20:58:27.713][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][16210][19-02-05T20:58:27.713][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][16210][19-02-05T20:58:27.713][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][16210][19-02-05T20:59:12.713][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][16210][19-02-05T20:59:12.713][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][16210][19-02-05T20:59:12.713][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][16210][19-02-05T20:59:12.719][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][16210][19-02-05T20:59:12.719][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][16210][19-02-05T20:59:12.719][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][16210][19-02-05T20:59:12.719][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][16210][19-02-05T20:59:12.719][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][16210][19-02-05T20:59:12.719][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][16210][19-02-05T20:59:12.777][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][16210][19-02-05T20:59:12.777][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][16210][19-02-05T20:59:12.829][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][16210][19-02-05T20:59:12.917][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][16210][19-02-05T20:59:12.972][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][16210][19-02-05T20:59:12.972][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][16210][19-02-05T20:59:12.973][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][16210][19-02-05T20:59:57.973][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][16210][19-02-05T20:59:57.973][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][16210][19-02-05T20:59:57.973][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

**Comment by SilentSeir** [comment]
Alternate:

~/Desktop/join$ tail -f zilliqa-00001-log.txt 
[INFO][24856][19-02-06T19:28:44.481][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][24856][19-02-06T19:28:44.481][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][24856][19-02-06T19:28:44.488][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][24856][19-02-06T19:28:44.488][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][24856][19-02-06T19:28:44.489][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][24856][19-02-06T19:28:44.489][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][24856][19-02-06T19:28:44.489][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][24856][19-02-06T19:28:44.489][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][24856][19-02-06T19:28:44.687][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][24856][19-02-06T19:28:44.767][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][24856][19-02-06T19:28:44.939][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][24856][19-02-06T19:28:45.029][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][24856][19-02-06T19:28:45.140][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][24856][19-02-06T19:28:45.140][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][24856][19-02-06T19:28:45.140][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][24856][19-02-06T19:29:30.140][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][24856][19-02-06T19:29:30.140][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][24856][19-02-06T19:29:30.140][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][24856][19-02-06T19:29:30.151][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][24856][19-02-06T19:29:30.151][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][24856][19-02-06T19:29:30.151][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][24856][19-02-06T19:29:30.153][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][24856][19-02-06T19:29:30.153][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][24856][19-02-06T19:29:30.153][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][24856][19-02-06T19:29:30.222][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][24856][19-02-06T19:29:30.223][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][24856][19-02-06T19:29:30.311][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][24856][19-02-06T19:29:30.311][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][24856][19-02-06T19:29:30.311][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][24856][19-02-06T19:29:30.311][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][24856][19-02-06T19:29:30.311][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][24856][19-02-06T19:30:15.311][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][24856][19-02-06T19:30:15.311][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][24856][19-02-06T19:30:15.311][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][24856][19-02-06T19:30:15.321][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][24856][19-02-06T19:30:15.321][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][24856][19-02-06T19:30:15.321][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][24856][19-02-06T19:30:15.321][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][24856][19-02-06T19:30:15.321][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][24856][19-02-06T19:30:15.321][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][24856][19-02-06T19:30:15.326][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][24856][19-02-06T19:30:15.410][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][24856][19-02-06T19:30:15.410][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][24856][19-02-06T19:30:15.470][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][24856][19-02-06T19:30:15.552][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][24856][19-02-06T19:30:15.552][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][24856][19-02-06T19:30:15.552][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][24856][19-02-06T19:31:00.552][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][24856][19-02-06T19:31:00.552][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][24856][19-02-06T19:31:00.552][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

**Comment by SilentSeir** [comment]
join$ tail -f zilliqa-00001-log.txt 
[INFO][29733][19-02-06T23:13:04.168][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][29733][19-02-06T23:13:04.168][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][29733][19-02-06T23:13:04.168][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][29733][19-02-06T23:13:04.239][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][29733][19-02-06T23:13:04.334][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][29733][19-02-06T23:13:04.408][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][29733][19-02-06T23:13:04.455][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][29733][19-02-06T23:13:04.523][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][29733][19-02-06T23:13:04.523][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][29733][19-02-06T23:13:04.523][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][29733][19-02-06T23:13:49.523][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][29733][19-02-06T23:13:49.523][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][29733][19-02-06T23:13:49.523][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][29733][19-02-06T23:13:49.529][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][29733][19-02-06T23:13:49.529][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][29733][19-02-06T23:13:49.529][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][29733][19-02-06T23:13:49.529][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][29733][19-02-06T23:13:49.529][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][29733][19-02-06T23:13:49.529][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][29733][19-02-06T23:13:49.530][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][29733][19-02-06T23:13:49.530][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][29733][19-02-06T23:13:49.531][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][29733][19-02-06T23:13:49.578][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][29733][19-02-06T23:13:49.579][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][29733][19-02-06T23:13:49.579][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][29733][19-02-06T23:13:49.579][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][29733][19-02-06T23:14:34.579][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][29733][19-02-06T23:14:34.579][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][29733][19-02-06T23:14:34.579][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][29733][19-02-06T23:14:34.585][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][29733][19-02-06T23:14:34.585][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][29733][19-02-06T23:14:34.585][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][29733][19-02-06T23:14:34.585][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][29733][19-02-06T23:14:34.585][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][29733][19-02-06T23:14:34.585][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][29733][19-02-06T23:14:34.637][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][29733][19-02-06T23:14:34.688][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][29733][19-02-06T23:14:34.757][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][29733][19-02-06T23:14:34.827][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][29733][19-02-06T23:14:34.903][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][29733][19-02-06T23:14:34.904][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][29733][19-02-06T23:14:34.904][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][29733][19-02-06T23:15:19.904][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][29733][19-02-06T23:15:19.904][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][29733][19-02-06T23:15:19.904][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

RIP

**Comment by SilentSeir** [comment]
I just updated cuda to the most recent image using : 

`sudo docker pull zilliqa/zilliqa:v4.0.1-cuda`.

and still I am receiving this error : 

$ tail -f zilliqa-00001-log.txt 
[INFO][ 1813][19-02-08T17:51:19.414][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-08T17:51:19.414][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-08T17:51:19.415][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-08T17:51:19.415][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-08T17:51:19.415][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-08T17:51:19.415][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-08T17:51:19.470][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-08T17:51:19.514][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-08T17:51:19.572][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-08T17:51:19.644][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-08T17:51:19.695][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-08T17:51:19.695][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-08T17:51:19.695][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-08T17:52:04.696][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][ 1813][19-02-08T17:52:04.696][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1813][19-02-08T17:52:04.696][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1813][19-02-08T17:52:04.702][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-08T17:52:04.702][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-08T17:52:04.702][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-08T17:52:04.702][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-08T17:52:04.702][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-08T17:52:04.702][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-08T17:52:04.703][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-08T17:52:04.748][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-08T17:52:04.748][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-08T17:52:04.749][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-08T17:52:04.749][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-08T17:52:04.749][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-08T17:52:04.749][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-08T17:52:49.749][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][ 1813][19-02-08T17:52:49.749][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1813][19-02-08T17:52:49.749][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1813][19-02-08T17:52:49.756][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-08T17:52:49.756][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-08T17:52:49.756][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-08T17:52:49.756][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-08T17:52:49.756][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-08T17:52:49.756][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-08T17:52:49.824][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-08T17:52:49.877][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-08T17:52:49.918][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-08T17:52:49.993][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-08T17:52:50.038][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-08T17:52:50.038][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-08T17:52:50.038][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-08T17:53:35.039][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][ 1813][19-02-08T17:53:35.039][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][ 1813][19-02-08T17:53:35.039][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

**Comment by bb111189** [comment]
May I know what graphic card are you using? 

Also, did you install 
1, Cuda driver - https://developer.nvidia.com/cuda-downloads
2. nvidia-docker - https://github.com/NVIDIA/nvidia-docker#ubuntu-140416041804-debian-jessiestretch

**Comment by bb111189** [comment]
Our codebase have been updated to v4.0.2. Do pull the latest image.

Closing this issue. If you are still facing similar issue, feel free to reopen this issue and provides more information on your node set up.
