### ISSUE TITLE
18.04 vs 16.04 ? 

### ISSUE THREAD

**Issue by SilentSeir** [Zilliqa/Zilliqa#1384]
Are there any official servers on 18.04 LTS ?

**Comment by bmatthewshea** [comment]
If your question is 'does it work': 
yes-'sort of' - like most things on this chain.
I have run cpu node on debian stretch, too. With with compile problems I had to fix.
If you need help let me know.

https://github.com/Zilliqa/Zilliqa/pull/1280#issuecomment-459811518

**Comment by SilentSeir** [comment]
i7 cpu:

:~/Desktop/join$ tail -f zilliqa-00001-log.txt 
[INFO][ 7865][19-02-06T22:12:33.862][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 7865][19-02-06T22:12:33.862][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 7865][19-02-06T22:12:33.862][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 7865][19-02-06T22:12:33.923][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 7865][19-02-06T22:12:34.010][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 7865][19-02-06T22:12:34.090][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 7865][19-02-06T22:12:34.163][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 7865][19-02-06T22:12:34.244][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 7865][19-02-06T22:12:34.244][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 7865][19-02-06T22:12:34.244][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 7865][19-02-06T22:13:19.244][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][ 7865][19-02-06T22:13:19.244][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 7865][19-02-06T22:13:19.244][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 7865][19-02-06T22:13:19.250][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 7865][19-02-06T22:13:19.250][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 7865][19-02-06T22:13:19.250][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 7865][19-02-06T22:13:19.250][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 7865][19-02-06T22:13:19.250][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 7865][19-02-06T22:13:19.250][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 7865][19-02-06T22:13:19.251][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 7865][19-02-06T22:13:19.251][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 7865][19-02-06T22:13:19.252][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 7865][19-02-06T22:13:19.298][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 7865][19-02-06T22:13:19.299][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 7865][19-02-06T22:13:19.299][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 7865][19-02-06T22:13:19.299][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 7865][19-02-06T22:14:04.299][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][ 7865][19-02-06T22:14:04.299][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 7865][19-02-06T22:14:04.299][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 7865][19-02-06T22:14:04.305][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 7865][19-02-06T22:14:04.305][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 7865][19-02-06T22:14:04.305][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 7865][19-02-06T22:14:04.305][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 7865][19-02-06T22:14:04.305][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 7865][19-02-06T22:14:04.305][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 7865][19-02-06T22:14:04.362][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 7865][19-02-06T22:14:04.409][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 7865][19-02-06T22:14:04.474][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 7865][19-02-06T22:14:04.557][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 7865][19-02-06T22:14:04.616][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 7865][19-02-06T22:14:04.616][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 7865][19-02-06T22:14:04.616][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 7865][19-02-06T22:14:49.616][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][ 7865][19-02-06T22:14:49.616][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][ 7865][19-02-06T22:14:49.616][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

**Comment by bmatthewshea** [comment]
Nothing probably wrong. As I have come to learn by trail and error, you may need ot wait until next ds epoch? You may be blacklisted. Next one is in about 1/2 hour from time this posted Restart your Zil binary then? Took a day for me? No settings changed.

https://forum.zilliqa.com/t/fetchofflinelookups-timeout/296/18?u=bmatthewshea

**Comment by SilentSeir** [comment]
I will keep trying. 
In the meantime I am a lookup node. 
[INFO][17837][19-02-06T22:33:48.572][liqa/Zilliqa.cpp:295][operator()          ] I am a lookup node.
[INFO][17837][19-02-06T22:33:48.573][liqa/Zilliqa.cpp:297][operator()          ] API Server started successfully

**Comment by bmatthewshea** [comment]
block 4600 coming up.. 4596 now.

**Comment by evesnow91** [comment]
Hi @SilentSeir do check if you have enabled port forwarding. This looks like a network error.

Also, do not change the _constants.xml_ file for the `LOOKUP_NODE_MODE` parameter. Leave it as `false`.

**Comment by SilentSeir** [comment]
According to my router both 33133 and 4202 are being forwarded..

When i run  ./launch_docker.sh --cuda I recieve this: 


tail -f zilliqa-00001-log.txt 
	stack dump [6]  zilliqa() [0x762101]
	stack dump [7]  zilliqa() [0x4c87da]
	stack dump [8]  /usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8c80 [0x7fdc58235c80]
	stack dump [9]  /lib/x86_64-linux-gnu/libpthread.so.0+0x76ba [0x7fdc57a486ba]
	stack dump [10]  /lib/x86_64-linux-gnu/libc.so.6clone+0x6d [0x7fdc5777e41d]

Exiting after fatal event  (FATAL). Fatal type:  SIGABRT
Log content flushed sucessfully to sink

"g3log g3FileSink shutdown at: 16:45:24 047826

**Comment by bb111189** [comment]
May I know what graphic card are you using?

Also, did you install
1, Cuda driver - https://developer.nvidia.com/cuda-downloads
2. nvidia-docker - https://github.com/NVIDIA/nvidia-docker#ubuntu-140416041804-debian-jessiestretch

**Comment by lazaridiscom** [comment]
> like most things on this chain it takes guess work since no one will answer readily.

So, zilliqa has issues with usability / dev/user-experience?

**Comment by bb111189** [comment]
Closing this issue. Refer to #1409

**Comment by lazaridiscom** [comment]
@bb111189 , why did you close this issue? 

Ubuntu 18.04 functionality is of my interest, and it was not answered yet.

Additionally, I just ask another user here about his experience.

Isn't this here an open project resource?

**Comment by bb111189** [comment]
We are aware that many community members did build it on 18.04 or other Debian distribution. However, as of right now, the officially supported version is 16.04 LTS. We may consider moving forward to the new version of Ubuntu down the road. 

Do note that this issue deviated to other technical issue by the original issue creator **after the first post**. We have resolved help his query in a separate issue in #1409 promptly . Hence, we close this issue to put a closure to all tthe other issues he mentioned in this issue. 

If you want to query about the experience, do DM the person directly if possible. As per open source project norm, the issue tracker is for reporting issues to the developer only and not for conducting interviews. I hope you can understand that.  Thank you.

**Comment by lazaridiscom** [comment]
@bb111189 , please reflect, realize/understand your wrong-doing, and correct your processes.

@bmatthewshea , are you still active on this project? May I ask you what your comment was about, the one which got deleted? https://github.com/Zilliqa/Zilliqa/issues/1384#event-2123069360
