### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by SilentSeir** [Zilliqa/Zilliqa#1396]
[INFO][    1][19-02-08T21:14:27.352][ctoryService.cpp:382][SetState            ] [Epoch 0] DS State = POW_SUBMISSION
[INFO][    1][19-02-08T21:14:27.352][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][    1][19-02-08T21:14:27.355][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][    1][19-02-08T21:14:27.369][liqa/Zilliqa.cpp:143][Zilliqa             ] BEG
[INFO][    1][19-02-08T21:14:27.524][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][    1][19-02-08T21:14:27.536][BlockStorage.cpp:938][ResetDB             ] END
[INFO][    1][19-02-08T21:14:27.536][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][    1][19-02-08T21:14:27.548][BlockStorage.cpp:938][ResetDB             ] END
[INFO][    1][19-02-08T21:14:27.548][etwork/Guard.cpp:241][Init                ] Updating lists
[INFO][    1][19-02-08T21:14:27.548][etwork/Guard.cpp:225][ValidateRunTimeEnvir] BEG
[INFO][    1][19-02-08T21:14:27.548][etwork/Guard.cpp:225][ValidateRunTimeEnvir] END
[INFO][    1][19-02-08T21:14:27.571][Network/Guard.cpp:76][UpdateDSGuardlist   ] Entries = 420
[INFO][    1][19-02-08T21:14:27.619][etwork/Guard.cpp:109][UpdateShardGuardlist] Entries = 1200
[INFO][    1][19-02-08T21:14:27.619][etwork/Guard.cpp:248][Init                ] Adding Priv IPs to Exclusion List
[INFO][    1][19-02-08T21:14:27.620][liqa/Zilliqa.cpp:143][Zilliqa             ] END
[INFO][    1][19-02-08T21:14:27.620][work/P2PComm.cpp:716][StartMessagePump    ] BEG
[INFO][ 1810][19-02-08T21:14:27.620][libNode/Node.cpp:110][Install             ] BEG
[INFO][ 1810][19-02-08T21:14:27.620][libNode/Node.cpp:264][AddGenesisInfo      ] BEG
[INFO][ 1810][19-02-08T21:14:27.620][libNode/Node.cpp:227][Init                ] BEG
[INFO][ 1810][19-02-08T21:14:27.620][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.632][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.632][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.643][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.643][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.654][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.654][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.665][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.665][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.677][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.677][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.687][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.687][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.699][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.699][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.711][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.711][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.723][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.723][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.735][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.735][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.747][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.747][BlockStorage.cpp:938][ResetDB             ] BEG
[INFO][ 1810][19-02-08T21:14:27.759][BlockStorage.cpp:938][ResetDB             ] END
[INFO][ 1810][19-02-08T21:14:27.759][ce/Retriever.cpp:300][CleanAll            ] Reset DB Succeed
[INFO][ 1810][19-02-08T21:14:27.769][/AccountStore.cpp:41][Init                ] BEG
[INFO][ 1810][19-02-08T21:14:27.769][/AccountStore.cpp:52][InitSoft            ] BEG
[INFO][ 1810][19-02-08T21:14:27.769][/AccountStore.cpp:75][InitRevertibles     ] BEG
[INFO][ 1810][19-02-08T21:14:27.827][tractStorage.cpp:226][InitRevertibles     ] BEG
[INFO][ 1810][19-02-08T21:14:27.827][tractStorage.cpp:226][InitRevertibles     ] END
[INFO][ 1810][19-02-08T21:14:27.827][/AccountStore.cpp:75][InitRevertibles     ] END
[INFO][ 1810][19-02-08T21:14:27.827][/AccountStore.cpp:64][InitTemp            ] BEG
[INFO][ 1810][19-02-08T21:14:27.827][tractStorage.cpp:364][InitTempState       ] BEG
[INFO][ 1810][19-02-08T21:14:27.827][tractStorage.cpp:364][InitTempState       ] END
[INFO][ 1810][19-02-08T21:14:27.827][/AccountStore.cpp:64][InitTemp            ] END
[INFO][ 1810][19-02-08T21:14:27.827][/AccountStore.cpp:52][InitSoft            ] END
[INFO][ 1810][19-02-08T21:14:27.874][/AccountStore.cpp:41][Init                ] END
[INFO][ 1810][19-02-08T21:14:27.875][Synchronizer.cpp:108][InitializeGenesisBlo] BEG
[INFO][ 1810][19-02-08T21:14:27.876][/BlockStorage.cpp:50][PutBlock            ] Stored DSBlock num = 0
[INFO][ 1810][19-02-08T21:14:27.876][BlockStorage.cpp:498][PutMetadata         ] BEG
[INFO][ 1810][19-02-08T21:14:27.876][BlockStorage.cpp:498][PutMetadata         ] END
[INFO][ 1810][19-02-08T21:14:27.876][/BlockStorage.cpp:53][PutBlock            ] Stored TxBlock num = 0
[INFO][ 1810][19-02-08T21:14:27.876][Synchronizer.cpp:108][InitializeGenesisBlo] END
[INFO][ 1810][19-02-08T21:14:27.876][lockLinkChain.cpp:76][AddBlockLink        ] Index      = 0
[INFO][ 1810][19-02-08T21:14:27.876][lockLinkChain.cpp:77][AddBlockLink        ] DS Index   = 0
[INFO][ 1810][19-02-08T21:14:27.876][lockLinkChain.cpp:78][AddBlockLink        ] Block type = 0
[INFO][ 1810][19-02-08T21:14:27.876][lockLinkChain.cpp:79][AddBlockLink        ] Block hash = 0800bfda2b715fe7e401f7cf73182f072f8459318cb4bb90d195f681c5bbebdd
[INFO][ 1810][19-02-08T21:14:27.876][libNode/Node.cpp:227][Init                ] END
[INFO][ 1810][19-02-08T21:14:27.876][libNode/Node.cpp:264][AddGenesisInfo      ] END
[INFO][ 1810][19-02-08T21:14:27.876][libNode/Node.cpp:421][Prepare             ] BEG
[INFO][ 1810][19-02-08T21:14:27.876][ator/Mediator.cpp:61][UpdateDSBlockRand   ] BEG
[INFO][ 1810][19-02-08T21:14:27.876][ator/Mediator.cpp:65][UpdateDSBlockRand   ] Genesis DSBlockchain
[INFO][ 1810][19-02-08T21:14:27.876][ator/Mediator.cpp:61][UpdateDSBlockRand   ] END
[INFO][ 1810][19-02-08T21:14:27.876][ator/Mediator.cpp:82][UpdateTxBlockRand   ] BEG
[INFO][ 1810][19-02-08T21:14:27.876][ator/Mediator.cpp:85][UpdateTxBlockRand   ] Genesis txBlockchain
[INFO][ 1810][19-02-08T21:14:27.876][ator/Mediator.cpp:82][UpdateTxBlockRand   ] END
[INFO][ 1810][19-02-08T21:14:27.876][ibNode/Node.cpp:1583][SetState            ] [Epoch 1] Node State = POW_SUBMISSION
[INFO][ 1810][19-02-08T21:14:28.454][c/libPOW/pow.cpp:756][InitCUDA            ] Generate dag Nvidia GPU #0
[INFO][ 1810][19-02-08T21:14:28.477][c/libPOW/pow.cpp:778][InitCUDA            ] CUDA GPU initialized in POW
[INFO][ 1810][19-02-08T21:14:28.477][libNode/Node.cpp:421][Prepare             ] END
[INFO][ 1810][19-02-08T21:14:28.477][libNode/Node.cpp:110][Install             ] END
[INFO][ 1810][19-02-08T21:14:28.477][lliqa/Zilliqa.cpp:46][LogSelfNodeInfo     ] Public Key (Len=33): xxxxxxxxxxxxx
[INFO][ 1810][19-02-08T21:14:28.477][lliqa/Zilliqa.cpp:58][LogSelfNodeInfo     ] My address is xxxxxxxxxxxxxxxx and port is 33133
[INFO][ 1810][19-02-08T21:14:28.477][liqa/Zilliqa.cpp:219][operator()          ] Sync as a new node
[INFO][ 1810][19-02-08T21:14:28.477][okup/Lookup.cpp:3558][SetSyncType         ] [Epoch 1] Set sync type to 1
[INFO][ 1810][19-02-08T21:14:28.477][libNode/Node.cpp:931][StartSynchronization] BEG
[INFO][ 1810][19-02-08T21:14:28.477][ibNode/Node.cpp:1583][SetState            ] [Epoch 1] Node State = SYNC
[INFO][ 1810][19-02-08T21:14:28.477][libNode/Node.cpp:931][StartSynchronization] END
[INFO][ 1810][19-02-08T21:14:28.477][liqa/Zilliqa.cpp:276][operator()          ] I am a ds/normal node.
[INFO][ 1810][19-02-08T21:14:28.477][liqa/Zilliqa.cpp:291][operator()          ] GetWork Mining Server not enable
[INFO][ 1813][19-02-08T21:14:28.477][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1813][19-02-08T21:14:28.477][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1813][19-02-08T21:14:28.481][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-08T21:14:28.481][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-08T21:14:28.481][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-08T21:14:28.481][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-08T21:14:28.481][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-08T21:14:28.481][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-08T21:14:28.524][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-08T21:14:28.566][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-08T21:14:28.609][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-08T21:14:28.651][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-08T21:14:28.703][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-08T21:14:28.703][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-08T21:14:28.703][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-08T21:15:13.703][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][ 1813][19-02-08T21:15:13.703][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1813][19-02-08T21:15:13.703][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1813][19-02-08T21:15:13.709][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-08T21:15:13.709][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-08T21:15:13.709][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-08T21:15:13.709][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-08T21:15:13.709][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-08T21:15:13.709][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-08T21:15:13.757][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-08T21:15:13.758][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-08T21:15:13.758][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-08T21:15:13.811][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-08T21:15:13.811][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-08T21:15:13.811][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-08T21:15:13.811][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-08T21:15:58.811][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][ 1813][19-02-08T21:15:58.812][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1813][19-02-08T21:15:58.812][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1813][19-02-08T21:15:58.818][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-08T21:15:58.818][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-08T21:15:58.818][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-08T21:15:58.818][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-08T21:15:58.818][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-08T21:15:58.818][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-08T21:15:58.863][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-08T21:15:58.914][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-08T21:15:58.961][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-08T21:15:58.962][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-08T21:15:59.009][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-08T21:15:59.009][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-08T21:15:59.009][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-08T21:16:44.009][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][ 1813][19-02-08T21:16:44.009][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][ 1813][19-02-08T21:16:44.009][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

**Comment by bb111189** [comment]
Closing this issue. If you are still facing similar issue, feel free to reopen this issue and provides more information on your node set up.
