### ISSUE TITLE
[WEBSITE] Missing Section for End-Users

### ISSUE THREAD

**Issue by lazaridiscom** [Zilliqa/Zilliqa#1401]
The current zilliqa website has several weaknesses.

One which comes up immediately when visiting the site is the **missing "End-User" Section**, which should list tings like

* Wallet
* Explorer

## Dead Link

The Wallet is currently listed in the dev section

https://zilliqa.com/for-developers.html

and as a sidenote, it is a dead-link: https://wallet.zilliqa.com/home

## Actions

* Correct the dead-link
* Provide a End-User section on the website, which points to the basic end-user tools

**Comment by bb111189** [comment]
Thank for your feedback. We will look into the feedback and refine our website browsing experience

**Comment by lazaridiscom** [comment]
At this point, what I would need it the missing information:

* A list of wallets (ideally produced by zilliqa, but could be 3rd party, too)

questions (which your website should answer anyway) :

* is there a browser-wallet available (like e.g. AIWA for AION)
* can i use Ledger or Trezor hardware-wallet?
* which desktop-wallet is suggested?
* which phone-wallets?

**Comment by bb111189** [comment]
There is a community developed wallet. https://moonlet.xyz/

Ledger wallet support is in the work
