### ISSUE TITLE
Epoch 6094 error? 

### ISSUE THREAD

**Issue by SilentSeir** [Zilliqa/Zilliqa#1409]
Can someone from the development team please explain this... ?

**Comment by bb111189** [comment]
Hi, 

We really wish to help you but we wouldn't be able to help you in this case. You may need to be more precise in the issue reporting.
1. What was the error encountered? (Describe if possible and not dumping the last few lines of logs)
2. What was the setup of your node?
- Is it a manual build? docker build? with cuda? with opencl?
3. What version of the codebase did you use? 
4. The steps to reproduce the issues or how did you encounter this issue
5. Did you modify any files?
6. Are you behind a NAT? 
7. Any other useful information? 

It is ok not to provide an answer to all questions, but the more information you provide, the more we can understand the issue. Otherwise, posting the last few lines of logs or vague issues will not be helpful to us or you either. 

We are here to help but we do need more concrete information. We hope that you will understand it.

**Comment by SilentSeir** [comment]
I'm currently on the latest release 4.0.2

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
| 33%   24C    P8     6W / 151W |    276MiB /  8117MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2125      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      2176      G   /usr/bin/gnome-shell                          50MiB |
|    0      3261      G   /usr/lib/xorg/Xorg                           104MiB |
|    0      3393      G   /usr/bin/gnome-shell                          98MiB |
+-----------------------------------------------------------------------------+




Yesterday when i launched my miner It was stuck on epoch 6094. 
Today when i launched it appears I'm blacklisted? 

 tail -f zilliqa-00001-log.txt 
[INFO][ 1813][19-02-10T20:47:58.047][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-10T20:47:58.047][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-10T20:47:58.047][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-10T20:47:58.135][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-10T20:47:58.242][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-10T20:47:58.317][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-10T20:47:58.403][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-10T20:47:58.469][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-10T20:47:58.469][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-10T20:47:58.469][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-10T20:48:43.469][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 1/3 times
[INFO][ 1813][19-02-10T20:48:43.469][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1813][19-02-10T20:48:43.469][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1813][19-02-10T20:48:43.476][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-10T20:48:43.476][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-10T20:48:43.476][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-10T20:48:43.476][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-10T20:48:43.476][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-10T20:48:43.476][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-10T20:48:43.477][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-10T20:48:43.478][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-10T20:48:43.478][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-10T20:48:43.479][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-10T20:48:43.479][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-10T20:48:43.479][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-10T20:48:43.479][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][ 1813][19-02-10T20:49:28.479][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 2/3 times
[INFO][ 1813][19-02-10T20:49:28.479][okup/Lookup.cpp:2923][GetOfflineLookupNode] BEG
[INFO][ 1813][19-02-10T20:49:28.479][ookup/Lookup.cpp:125][SetLookupNodes      ] BEG
[INFO][ 1813][19-02-10T20:49:28.487][ookup/Lookup.cpp:125][SetLookupNodes      ] END
[INFO][ 1813][19-02-10T20:49:28.487][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] BEG
[INFO][ 1813][19-02-10T20:49:28.487][e/Messenger.cpp:5626][SetLookupGetOfflineL] BEG
[INFO][ 1813][19-02-10T20:49:28.487][e/Messenger.cpp:5626][SetLookupGetOfflineL] END
[INFO][ 1813][19-02-10T20:49:28.487][okup/Lookup.cpp:2899][ComposeGetOfflineLoo] END
[INFO][ 1813][19-02-10T20:49:28.487][ookup/Lookup.cpp:440][SendMessageToLookupN] BEG
[INFO][ 1813][19-02-10T20:49:28.602][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.184.239.252:33133>
[INFO][ 1813][19-02-10T20:49:28.766][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.210.214.209:33133>
[INFO][ 1813][19-02-10T20:49:28.832][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.13.140:33133>
[INFO][ 1813][19-02-10T20:49:28.916][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <54.149.110.46:33133>
[INFO][ 1813][19-02-10T20:49:28.991][ookup/Lookup.cpp:460][SendMessageToLookupN] Sending to lookup <34.220.11.234:33133>
[INFO][ 1813][19-02-10T20:49:28.991][ookup/Lookup.cpp:440][SendMessageToLookupN] END
[INFO][ 1813][19-02-10T20:49:28.991][okup/Lookup.cpp:2923][GetOfflineLookupNode] END
[WARN][  951][19-02-10T20:50:08.826][work/P2PComm.cpp:211][SendMessageSocketCor] Socket connect failed. Code = 110 Desc: Connection timed out. IP address: <34.220.11.234:33133>
[WARN][  951][19-02-10T20:50:08.826][work/P2PComm.cpp:216][SendMessageSocketCor] [blacklist] Encountered 110 (Connection timed out). Adding 34.220.11.234 to blacklist
[INFO][  951][19-02-10T20:50:08.826][ork/Blacklist.cpp:54][Add                 ] Excluded 34.220.11.234
[WARN][  951][19-02-10T20:50:08.826][work/P2PComm.cpp:281][SendMessageCore     ] Socket connect failed 1/1. IP address: <34.220.11.234:33133>
[WARN][ 1813][19-02-10T20:50:13.991][libNode/Node.cpp:908][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][ 1813][19-02-10T20:50:13.991][libNode/Node.cpp:917][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][ 1813][19-02-10T20:50:13.991][libNode/Node.cpp:936][operator()          ] Cannot rejoin currently

My ports are open and all of my config files are default except for what was noted to be changed in the mining docs. 

Thank you for taking the time to work out the bugs.

**Comment by bb111189** [comment]
Have you redownloaded https://mainnet-join.zilliqa.com/configuration.tar.gz ?

It seems like your node might be still on v4.0.1 as that Epoch number was likely to be from v4.0.1

**Comment by SilentSeir** [comment]
Good call.
