### ISSUE TITLE
[WEBSITE] Missing Mining Quick-Start

### ISSUE THREAD

**Issue by lazaridiscom** [Zilliqa/Zilliqa#1410]
## Experience

https://zilliqa.com/for-miners.html

Visiting the "Miners" section of the website, in order to quickly setup mining.

The  full-screen landing-page has just this content:

> For Miners
> We are inviting all miners to test out the process of joining our network as a public node.

## Expected

The landing-page gives me **immediately** the relevant information, **ideally just a few command-line instructions** which start the mining process.

## Possible Actions

* Revise the Mining page to provide immediately information (instead of a essentially blank page with a title)
* Drastically simplify the Mining Guide (https://github.com/Zilliqa/Zilliqa/wiki/Mining), thus experienced IT folks is not annoyed by the complexity, and not so experienced people are not scared away by the amount of information.
  * means: simple-first, appendix, possible split, cli-focused

## Possible Goal

* max. 5 cli instructions which start mining process

**Comment by AmritKumar** [comment]
@lazaridiscom Please move comments on the website to other channels. As for the mining wiki, you may push a PR that improves the doc.

**Comment by lazaridiscom** [comment]
Quiz: why do I answer 2 times "No, I won't" ?

**Comment by lazaridiscom** [comment]
Note to readers:

Quiz Solution A: Because this repository is the valid resource for Zilliqa-Website related issues.

Quiz Solution B: Because the effort to fix the documentation goes into weeks. It involves fixing the (flawed, in context of usability) underlying systems.

**Comment by AmritKumar** [comment]
Note to readers and **to the OP**: This **is not** the relevant repository for Zilliqa website. It is a C++ codebase to report bugs or issues in the codebase. The team handling website does not contribute to this codebase so any website related comments is completely irrelevant here. Thank you for your understanding.

**Comment by AmritKumar** [comment]
Please report website related issues through other channels and the relevant team will take action accordingly.

**Comment by lazaridiscom** [comment]
Note to readers: this is the point where one has to give up...
