### ISSUE TITLE
[WEBSITE] Missing DApp-Dev Quick-Start

### ISSUE THREAD

**Issue by lazaridiscom** [Zilliqa/Zilliqa#1411]
## Experience

https://zilliqa.com/for-developers.html

Visiting the "For Developers" section of the website, in order to quickly start with development.

The  full-screen landing-page has just this content:

> For Developers
> Learn about the tools, reasons and incentives to build on Zilliqa’s blockchain.

What follows it a collection of links, partially dead. It is unclear where and how to start.

## Expected

The landing-page gives me **immediately** the relevant information, ideally a single download (or git clone).

## Possible Actions

=> the Developer-Section of the site needs a full rework

**Comment by AmritKumar** [comment]
@lazaridiscom This is not relevant to this repository and hence will be closed. Please leave your feedback on the website via other channels (e.g., Gitter or Telegram).

**Comment by lazaridiscom** [comment]
Why would I use chat-systems to file issues? I leave this to amateurs.
