### ISSUE TITLE
Provide Support for ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ghost** [Zilliqa/Zilliqa#1415]
## Status

ubuntu 16.04 LTS is the officially supported OS

## Expected

ubuntu 18.04 LTS is added to the supported OS

## Related

* https://github.com/Zilliqa/Zilliqa/issues/1384
* https://github.com/Zilliqa/Zilliqa/pull/1280

**Comment by SilentSeir** [comment]
I am running a node on 18.04 
It is supported.

**Comment by lazaridiscom** [comment]
It is not "officially supported", by the team:

> We are aware that many community members did build it on 18.04 or other Debian distribution. However, as of right now, the officially supported version is 16.04 LTS. We may consider moving forward to the new version of Ubuntu down the road.

From: https://github.com/Zilliqa/Zilliqa/issues/1384#issuecomment-462230430
