### ISSUE TITLE
[GOVERNANCE] Deleted Comment, Request for Clarifications

### ISSUE THREAD

**Issue by lazaridiscom** [Zilliqa/Zilliqa#1416]
I try to get an overview of the project by reviewing a few issues.

This is how I hit on a deleted comment:

https://github.com/Zilliqa/Zilliqa/issues/1384#event-2123069360

As usual with deleted comments, one can not verify the validity of the deletion.

So my question:

Why was the comment deleted, and why is there not remark about it (from the person which deleted the comment) ?

**Comment by AmritKumar** [comment]
Closing this too as it does not concern the codebase and a thread is already live here: https://github.com/Zilliqa/Zilliqa/issues/1384#issuecomment-462304617 in case the OP is looking for comments.

**Comment by AmritKumar** [comment]
A gentle suggestion to the OP not to abuse the issue feature on GitHub. Let's use it to report potential bugs or issues in the codebase.

**Comment by lazaridiscom** [comment]
Wow! You are really really confusing things!!!
