### ISSUE TITLE
[WEBSITE] Where is the Issue-Tracker for the Website?

### ISSUE THREAD

**Issue by lazaridiscom** [Zilliqa/Zilliqa#1424]
Someone plays "wild-west" on the project-resources, and shuts-down valid WEBSITE feedback and even Issues which affect censorship and address the project GOVERNANCE ( #1416).

Question:

Which issue-tracker can be used for Zilliqa Website related issues and for Zilliqa Project Governance related issues? (note: not a chat-system, not a non-public resouces, but a public(!) issue-tracker, naturally on github).

Question 2:

If there is not Issue-Tracker available, why don't you provide one (takes 5 minutes)

Question 3:

Why do you close the issues (#1410, #1411), despite their validity (loosing this way the information, and disrespecting the effort of the contributor that filed them).

Question 4:

Why was Issue #1401 not closed? (at least be consistent with your irrationality)

Question 5:

Is there really no person on this team which realizes that closing issues in that way is simply unprofessional and irresponsible?

**Comment by evesnow91** [comment]
You can send your feedbacks to enquiry@zilliqa.com. This is not your playground for random non-code related issues.
