### ISSUE TITLE
[COMPLAINT] Abusive Behaviour of Team Members

### ISSUE THREAD

**Issue by lazaridiscom** [Zilliqa/Zilliqa#1425]
**(Please note that I'm addressing here publicly and formally the **Zilliqa Leadership**. I will not(!) use any other medium for my complaint.)**

To the Zilliqa Management/Leadership.

2 Developers continue to close my (perfectly valid) issues without replying, having a **totally unfounded** (and unseen) fixation on "code-only issues". 

Latest incident: https://github.com/Zilliqa/Zilliqa/issues/1424, which was even "LOCKED" (I cannot respond to this unbelievable rudeness).

Please ensure that my issues are reopened and processed (at a minimum, just point me to the resource I asked for: a public issues-tracker for website-related issues).

**Comment by evesnow91** [comment]
This is your last warning. One more issue that is non-code related by you will result in permanent ban from posting on this repository.
