### ISSUE TITLE
[Remote Mining] the timeout of DS PoW is wrong 

### ISSUE THREAD

**Issue by deepgully** [Zilliqa/Zilliqa#1434]
The timeout of PoW work is fixed "POW_WINDOW_IN_SECONDS" currently, which is not correct for DS PoW.
When the DS PoW send to proxy, the Shard PoW had taken up some time of PoW window, we should subtract the time taken by Shard PoW.

https://github.com/Zilliqa/Zilliqa/blob/0af01d4cb1333ed00d1177219946db0478d9901d/src/libPOW/pow.cpp#L372-L377

**Comment by deepgully** [comment]
@ShengguangXiao could you help to fix?

**Comment by ShengguangXiao** [comment]
@deepgully I will handle it
