### ISSUE TITLE
about 1 hour ago

### ISSUE THREAD

**Issue by SilentSeir** [Zilliqa/Zilliqa#1465]
# of DS Blocks
197

# of Tx Blocks
19599

**Comment by SilentSeir** [comment]
about 2 hours ago

**Comment by SilentSeir** [comment]
about 3 hours ago

**Comment by bb111189** [comment]
Hello. Please use the issue tracker to report bugs. These are not bugs.

**Comment by SilentSeir** [comment]
If the network is down, which it appears to be, that is a pretty large issue.

**Comment by bb111189** [comment]
We will provide an update in other media such as Telegram. The issue tracker is not used to report network stalls.
