### ISSUE TITLE
Rejected Shares

### ISSUE THREAD

**Issue by SilentSeir** [Zilliqa/Zilliqa#1474]
Is there any way you can extend the window of opportunity for data to be received ?

**Comment by SilentSeir** [comment]
[INFO][  214][19-02-23T01:15:47.271][okup/Lookup.cpp:2195][InitMining          ] [Epoch 20401] Not yet connected to network

**Comment by SilentSeir** [comment]
[WARN][ 1844][19-02-23T03:18:03.158][etWorkServer.cpp:187][UpdateCurrentResult ] newResult is not success

**Comment by SilentSeir** [comment]
[WARN][ 1829][19-02-27T23:40:37.915][c/libPOW/pow.cpp:628][MineFullGPUThread   ] Time out while mining pow result, time passed in seconds 61

**Comment by bb111189** [comment]
It is fixed. As such, you will need more hashing power in order to find the solution in the given time window.
