### ISSUE TITLE
`using namespace` is used in header file

### ISSUE THREAD

**Issue by Gnnng** [Zilliqa/Zilliqa#150]
Currently two places:

https://github.com/Zilliqa/Zilliqa/blob/1e39b692900b59fd4b1c23985512e2edc6ca6f62/src/libUtils/TimeLockedFunction.h#L29

https://github.com/Zilliqa/Zilliqa/blob/1e39b692900b59fd4b1c23985512e2edc6ca6f62/src/libServer/JSONConversion.h#L31-L32

The reason why not writing in this way is [here](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rs-using-directive)

**Comment by KaustubhShamshery** [comment]
Removed partially in #132 , However many of the *.h files which include "TimeLockedFunctions.h" also are using the namespace implicitly.

**Comment by Gnnng** [comment]
This was fixed in #567
