### ISSUE TITLE
Data provided by the json API is incomplete

### ISSUE THREAD

**Issue by hlb8122** [Zilliqa/Zilliqa#1578]
To find the number of confirmations a block enjoys I must: subtract the block number given in the latest block from the block number of the block of interest.

How do I do this for a transaction? Given a transaction ID, the GetTransaction method doesn't provide the number of confirmations nor does it provide the block ID of the block it's contained within... It's seemingly impossible to perform this simple task with the current API.

**Comment by evesnow91** [comment]
There is finality in Zilliqa. There is no need for confirmations.

**Comment by hlb8122** [comment]
There is still a need however to see which block a transaction lies within?
