### ISSUE TITLE
RPC method GetBalance fail

### ISSUE THREAD

**Issue by lich666dead** [Zilliqa/Zilliqa#1585]
when call GetBalance at address 0x4a99f46d0d34daf4410ad1e9159752668b9d733a, 
35756910000000 or 19932000000000! every request. If sending more requests that response may be 35756910000000 or 19932000000000! We Can make sure just update page on https://dev-explorer.zilliqa.com/address/4a99f46d0d34daf4410ad1e9159752668b9d733a

**Comment by KaustubhShamshery** [comment]
There was an issue with API, please check if it is resolved now. Thanks.

**Comment by lich666dead** [comment]
all right
