### ISSUE TITLE
Compile error tag/v4.4.1

### ISSUE THREAD

**Issue by armatusmiles** [Zilliqa/Zilliqa#1602]
tag/v4.4.1 has compile warnings with clang-7. That's why build can be successful only without [-Werror](https://github.com/Zilliqa/Zilliqa/blob/tag/v4.4.1/CMakeLists.txt#L216)

**Comment by bb111189** [comment]
Clang-7 is still currently not yet supported. But we have been exploring Clang-7 support. 
https://github.com/Zilliqa/Zilliqa/pull/1473
