### ISSUE TITLE
ZILIP0000: Zilliqa Improvement Proposal 0000: Provide a standardized repository for improvement proposals

### ISSUE THREAD

**Issue by csajedi** [Zilliqa/Zilliqa#1619]
Hello, 
This is not a technical proposal per-se and many of my comments are not going to relate directly to implementation of the node and network as found in this repository, however like [Ethereum ](https://github.com/ethereum/EIPs)and other public blockchains, Zilliqa's community will require a place to gather and discuss the development of standards. I therefore put forward ZILIP0000: create a repository for improvement proposals here in the zilliqa github organization.

**Comment by evesnow91** [comment]
Hey @csajedi ,

We are thinking of something similar to SLIP format. However, do let us stabilize the platform first so that we can write out the documentation needed to springboard such community discussion.

**Comment by csajedi** [comment]
@evesnow91 thanks for the clarity. Can you put a non-binding estimate on when that will happen? I applied for an ecosystem grant and want to generate healthy discussion and multiparty interest in the open source ecosystem surrounding ZIL but right now there isn't really a good place to nucleate discussion outside the forums which don't seem so active.

**Comment by evesnow91** [comment]
I am looking into your application. As for healthy debate, I suggest to resume it in the public technical forum, it is improving in visibility there as we promote more debates and discussion around our design choices. 

When the SLIP-like repository is set up around Q4 '19 as we stamp out the necessary documentations, we can shift more of such discussions there then. Meanwhile, as this repository has a strict limit on code-only discussions, I will be closing this issue as it is not code-related. Hope you understand.
