### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by csajedi** [Zilliqa/Zilliqa#1637]
When I follow the build instructions on the README.md I get a build error for g3log, there are a few related issues that have been closed due to user nonresponse so I will include the relevant logfiles. There were no cluse in the g3log issue tracker so I am at a loss for how to continue.
[CMakeError.log](https://github.com/Zilliqa/Zilliqa/files/3149676/CMakeError.log)
[CMakeOutput.log](https://github.com/Zilliqa/Zilliqa/files/3149677/CMakeOutput.log)

**Comment by bb111189** [comment]
Did you `git clone` the repo or download the files directly from github? 

We have the following submodule that needs to be cloned. 
https://github.com/Zilliqa/Zilliqa/blob/master/.gitmodules

We recommend you to use 
```
git clone git@github.com:Zilliqa/Zilliqa.git
```

**Comment by csajedi** [comment]
I used this set of instructions to attempt the build. I believe my use-case may be better served with Kaya for the time being but I'd still ultimately solve this issue. 
```
# download the lastest stable Zilliqa source code
$ git clone git@github.com:Zilliqa/Zilliqa.git
$ cd Zilliqa && git checkout tag/v4.6.0

# build Zilliqa binary
$ ./build.sh
```

**Comment by csajedi** [comment]
Update: by avoiding the ``` git checkout tag/v4.6.0``` and instead using master I was able to compile without issue
