### ISSUE TITLE
Support customized log path

### ISSUE THREAD

**Issue by Gnnng** [Zilliqa/Zilliqa#1643]
The log files are directly written into the working directory where the process is running. There's a need to store the logs into a separate directory, when

1. A system-wide log path is preferred, e.g., `/var/log`
2. A user would like to use sidecar container to rotate the log.

To avoid introducing breaking change when supporting this, we can keep the current behavior as the default while allowing a user to set a customized path.

**Comment by bb111189** [comment]
Already implemented. Issue closed
