### ISSUE TITLE
Repeat failed HTTP request during PoW window

### ISSUE THREAD

**Issue by Snuff** [Zilliqa/Zilliqa#1681]
Hello,

I have plenty of nodes configured to mine remotely through a proxy. Currently, If HTTP request to the proxy fails, due to any reasons, PoW round will be stopped. That leads to losing valid shares, mining revenue, and network instability. Here I want to review all request types, define impact, and propose a solution.

Example:

```
[SendWorkToProxy     ] Exception captured in jsonrpc api zil_requestWork,
 exception: Exception -32003 : Client connector error: libcurl error:
 28 -> Operation timed out
```

There are three types of request to proxy:
1. Send work to the proxy
2. Check for solution
3. Confirm verification of the solution

### Send work to the proxy

**Impact:** the node will stand idle till next round, a proxy might won't be able to provide enough works for miners.

**Solution:** repeat request till the end of the round every N seconds, considering lost time in work duration.

### Check for solution

**Impact:** the node will stand idle till next round, lost of mining revenue and losing a shard sometimes.

**Solution:** Don't stop PoW round.

### Confirm verification of the solution

**Impact:** UI glitch.

**Solution:** Repeat request 2-3 times.

Please, review my solutions and implement them.

**Comment by Swaggadan** [comment]
I seem to be having the same issue. 

`[WARN][  225][19-05-31T12:21:47.599][c/libPOW/pow.cpp:493][Sen                                                                  dWorkToProxy     ] Exception captured in jsonrpc api zil_reque                                                                  stWork, exception: Exception -32003 : Client connector error:                                                                   libcurl error: 7 -> Could not connect to http://zilpool:5000/`                                                                  api

**Comment by reb0rn21** [comment]
Same issue all nodes broken from today :(
zero reward even if the proxy find and verifie for miner, the node receive zero and stop submiting POW

I have only one DS node that work fine atm till it last without POW

**Comment by ShengguangXiao** [comment]
1. The zil_requestWork can have a retry mechanism
2. The mining proxy need to handle timeout exception, because it may affect process PoW request.

**Comment by Snuff** [comment]
Hi @ShengguangXiao, What do you mean by `mining proxy`? Software like https://github.com/DurianStallSingapore/Zilliqa-Mining-Proxy?

**Comment by ShengguangXiao** [comment]
> Hi @ShengguangXiao, What do you mean by `mining proxy`? Software like https://github.com/DurianStallSingapore/Zilliqa-Mining-Proxy?

@Snuff Yes, you are correct

**Comment by Snuff** [comment]
@ShengguangXiao Timeout error is on node side, not on mining proxy side. Is this fix related to the issue?

**Comment by ShengguangXiao** [comment]
> @ShengguangXiao Timeout error is on node side, not on mining proxy side. Is this fix related to the issue?

Node side will have another PR to fix the issue

**Comment by Snuff** [comment]
@ShengguangXiao, did you consciously not added retry mechanism for other PoW calls? I'm sure that it must be implemented for other calls, such as `CheckMiningResult` and `VerifyRemoteSolution`, too.

**Comment by ShengguangXiao** [comment]
> @ShengguangXiao, did you consciously not added retry mechanism for other PoW calls? I'm sure that it must be implemented for other calls, such as `CheckMiningResult` and `VerifyRemoteSolution`, too.

CheckMiningResult already have mechanism, VerifyRemoteSolution even failed will still continue, so these two steps can tolerate error already

**Comment by Snuff** [comment]
@ShengguangXiao CheckMiningResult doesn't have the mechanism: https://github.com/Zilliqa/Zilliqa/blob/a6bc4450457d35714eefdad821a6f6f132379705/src/libPOW/pow.cpp#L597 It returns false when catching an exception, it should continue polling instead.

**Comment by Snuff** [comment]
Same goes to https://github.com/Zilliqa/Zilliqa/blob/a6bc4450457d35714eefdad821a6f6f132379705/src/libPOW/pow.cpp#L577

**Comment by ShengguangXiao** [comment]
> Same goes to
> 
> https://github.com/Zilliqa/Zilliqa/blob/a6bc4450457d35714eefdad821a6f6f132379705/src/libPOW/pow.cpp#L577

I think here should return false, because in this scenario, it means the mining proxy has protocol problem, it should return result as the protocol definition

**Comment by Snuff** [comment]
@ShengguangXiao I believe node must be proxy-oriented as much as possible. E.g., forgive proxy mistakes and try to repeat the request if possible. If I were you, I would repeat the request even in this scenario.

**Comment by Snuff** [comment]
@ShengguangXiao Any news?

**Comment by Snuff** [comment]
@ShengguangXiao up

**Comment by ShengguangXiao** [comment]
@Snuff I will handle it soon

**Comment by Snuff** [comment]
Thanks!

**Comment by Canefis** [comment]
> Hello,
> 
> I have plenty of nodes configured to mine remotely through a proxy. Currently, If HTTP request to the proxy fails, due to any reasons, PoW round will be stopped. That leads to losing valid shares, mining revenue, and network instability. Here I want to review all request types, define impact, and propose a solution.
> 
> Example:
> 
> ```
> [SendWorkToProxy     ] Exception captured in jsonrpc api zil_requestWork,
>  exception: Exception -32003 : Client connector error: libcurl error:
>  28 -> Operation timed out
> ```
> 
> There are three types of request to proxy:
> 
>     1. Send work to the proxy
> 
>     2. Check for solution
> 
>     3. Confirm verification of the solution
> 
> 
> ### Send work to the proxy
> 
> **Impact:** the node will stand idle till next round, a proxy might won't be able to provide enough works for miners.
> 
> **Solution:** repeat request till the end of the round every N seconds, considering lost time in work duration.
> ### Check for solution
> 
> **Impact:** the node will stand idle till next round, lost of mining revenue and losing a shard sometimes.
> 
> **Solution:** Don't stop PoW round.
> ### Confirm verification of the solution
> 
> **Impact:** UI glitch.
> 
> **Solution:** Repeat request 2-3 times.
> 
> Please, review my solutions and implement them.

Can you post please how did you install this Mining Proxy, as I got difficulties with it. Durian/Zilproxy nobody reply, and also a lot of bugs in files.... thanks

**Comment by Canefis** [comment]
I have a same issue:

[WARN][  225][19-05-31T12:21:47.599][c/libPOW/pow.cpp:493][Sen                                                                  dWorkToProxy     ] Exception captured in jsonrpc api zil_reque                                                                  stWork, exception: Exception
