### ISSUE TITLE
Bug: Contract fields initialization

### ISSUE THREAD

**Issue by bogdan** [Zilliqa/Zilliqa#1691]
## Current Behavior

When a smart contract is deployed, the get state on that contract returns only a `_balance` field. Any manually defined field appears as part of the state only when contract processes the first transition successfully.

## Expected behavior

Contract state should return all field values of the contract right after the deployment without the necessity to execute any transition.

**Comment by evesnow91** [comment]
This fix will be scheduled for the next minor upgrade `v4.7.0`.

**Timeline:** 3rd week of July
**Current Status:**
- Scilla binary is updated to show the correct behavior
- Blockchain side will be updated soon
- Testing is not yet done

**Comment by evesnow91** [comment]
Updated since `v4.8.0`.
https://github.com/Zilliqa/Zilliqa/releases/tag/v4.8.0
