### ISSUE TITLE
[BUG] State root hash check failed

### ISSUE THREAD

**Issue by reb0rn21** [Zilliqa/Zilliqa#1699]
### Issue 
The node get stuck with
"State root hash check failed"

### Steps to Reproduce
Just run node for mining over proxy

#### Impact:
- [ ] Critical
- [x ] High
- [ ] Medium
- [ ] Low

### Additional Details
* Versions: latest docker 4.6.1
* Operating System:   ubuntu 18.04
* Installed packages:  docker imagine
* Screenshots / Log Files:
[zilliqa-log.txt](https://github.com/Zilliqa/Zilliqa/files/3318464/zilliqa-log.txt)
[download.log](https://github.com/Zilliqa/Zilliqa/files/3318466/download.log)

**Comment by evesnow91** [comment]
https://github.com/Zilliqa/Zilliqa/pull/1702

**Comment by reb0rn21** [comment]
Just had both node stop at 149500
and one node had reward and submited POW at 149499 and 149399...

+ diff is going up so someone have a solution as he is fine

**Comment by Swaggadan** [comment]
Same here, just lost another successful POW node to State root hash check error.

**Comment by bb111189** [comment]
Trying restarting the node. It shouldn't have the issue now.
