### ISSUE TITLE
[BUG] JSON-RPC server doesn't work: Connection refused

### ISSUE THREAD

**Issue by yivo** [Zilliqa/Zilliqa#1720]
I am running ZIL in Docker (zilliqa/zilliqa:v4.6.5).

Executing inside container: `curl -d '{"method": "SomeMethod", "jsonrpc": "2.0", "params": []}' -H "Content-Type: application/json" http://127.0.0.1:4201`

I am getting: `curl: (7) Failed to connect to 127.0.0.1 port 4201: Connection refused`

What's an issue?

**Comment by bb111189** [comment]
This is not a bug. Json RPC port 4201 is specially used for lookup node. The normal user currently will not be able to host a lookup node. 

Please refer to this following on how to query to local rpc status. 
https://forum.zilliqa.com/t/rpc-status-server-guide/596

**Comment by yivo** [comment]
@bb111189 Why I can't host lookup node? I need this to integrate ZIL to crypto exchange.
