### ISSUE TITLE
[BUG] CMake build target pollution

### ISSUE THREAD

**Issue by Gnnng** [Zilliqa/Zilliqa#1840]
### Issue 

Seems the top-level CMake targets got imported into the subtask of protobuf CMake build. 

Full travis log [here](https://travis-ci.com/Zilliqa/Zilliqa/builds/126587806#L706-L774).
```
WARNING: Target "data_migrate" requests linking to directory "/build/protobuf/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "genTxnBodiesFromS3" requests linking to directory "/build/protobuf/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "restore" requests linking to directory "/build/protobuf/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "validateDB" requests linking to directory "/build/protobuf/lib".  Targets may link only to libraries.  CMake is dropping the item.
...
```

This could also mean that other configuration settings like compiler flags are also affected. More investigation is needed.

### Steps to Reproduce

Any zilliqa build or docker build, for example see [here](https://travis-ci.com/Zilliqa/Zilliqa/builds/126587806#L706-L774).

#### Expected

No such warnings

#### Actual

CMake warnings

#### Impact:
- [ ] Critical
- [ ] High
- [x] Medium
- [ ] Low

### Additional Details
* Versions: v5.0.0-alpha.4
* Operating System:   
* Installed packages:  
* Screenshots / Log Files: https://travis-ci.com/Zilliqa/Zilliqa/builds/126587806#L706-L774

**Comment by ansnunez** [comment]
Unnecessary `PROTOBUF_LIBRARY` setting removed in #1873
