### ISSUE TITLE
In the JSON-RPC API, how do I get the transaction details in a block by the block number?

### ISSUE THREAD

**Issue by wshhz** [Zilliqa/Zilliqa#1868]
I want to get the transaction details in a block by block number. I only found the GetTxBlock interface in the JSON-RPC API, but there is no transaction information in the interface return value.

**Comment by bb111189** [comment]
You can use `GetTransactionsForTxBlock` to get a list of txns for a TxBlock. From there, you can use `GetTransaction` to get the transaction information

**Comment by wshhz** [comment]
i got it,tks
