### ISSUE TITLE
I can't convert the Timestamp

### ISSUE THREAD

**Issue by wshhz** [Zilliqa/Zilliqa#1878]
I called the GetTxBlock method to get the block data, but I can't convert the Timestamp inside. How can I get the block generation time?

**Comment by bb111189** [comment]
It is in unix epoch time 
https://www.epochconverter.com

There should be libraries in most programming languages to do such conversion.

**Comment by wshhz** [comment]
Oh, I thought it was expressed in seconds. I didn’t expect to use milliseconds. I understand,tks.

**Comment by wshhz** [comment]
@bb111189 Can you help me to apply for some tokens for my test network account? I will use ZIL Faucet to apply for tokens and report an error. This is my address: zil17npv7k7ac20wpv6rmku209sjs8zcvukz9r39u8.

**Comment by bb111189** [comment]
Test token sent!
