### ISSUE TITLE
I want to apply for some test net tokens.

### ISSUE THREAD

**Issue by wshhz** [Zilliqa/Zilliqa#1880]
Can you help me to apply for some tokens for my test network account? I will use ZIL Faucet to apply for tokens and report an error. This is my address: zil17npv7k7ac20wpv6rmku209sjs8zcvukz9r39u8.

**Comment by bb111189** [comment]
Done https://viewblock.io/zilliqa/tx/ebf3f30ffd2dc8ffd8cb897f1767d5aaf0650ee9d4f2b9ebc957f2b9933b19b1?network=testnet
