### ISSUE TITLE
[BUG] Cannot rejoin

### ISSUE THREAD

**Issue by liuxh-go** [Zilliqa/Zilliqa#1887]
I used the image of dockerv5.0.1 to run the mining node and the error was reported:
[INFO][ 1824][19-09-19T01:59:49.165][ookup/Lookup.cpp:473][SendMessageToLookupN] Sending to lookup <34.219.156.136:33133>
[WARN][   14][19-09-19T01:59:49.632][work/P2PComm.cpp:574][EventCallback       ] Header version wrong, received [22] while expected [1].
[INFO][ 1824][19-09-19T01:59:54.355][ookup/Lookup.cpp:473][SendMessageToLookupN] Sending to lookup <34.212.114.175:33133>
[INFO][ 1824][19-09-19T01:59:59.485][ookup/Lookup.cpp:473][SendMessageToLookupN] Sending to lookup <54.245.33.104:33133>
[INFO][ 1824][19-09-19T01:59:59.485][ookup/Lookup.cpp:453][SendMessageToLookupN] END
[INFO][ 1824][19-09-19T01:59:59.485][okup/Lookup.cpp:3486][GetOfflineLookupNode] END
[WARN][ 1824][19-09-19T02:00:44.485][ibNode/Node.cpp:1014][GetOfflineLookups   ] FetchOfflineLookups Timeout... tried 3/3 times
[WARN][ 1824][19-09-19T02:00:44.485][ibNode/Node.cpp:1023][GetOfflineLookups   ] Fetch offline lookup nodes failed
[WARN][ 1824][19-09-19T02:00:44.485][ibNode/Node.cpp:1042][operator()          ] Cannot rejoin currently

**Comment by bb111189** [comment]
The log provided is insufficient. Can you provide a more detailed log??
