### ISSUE TITLE
[BUG]Running mining node failed

### ISSUE THREAD

**Issue by liuxh-go** [Zilliqa/Zilliqa#1891]
### Issue 
I want to run a mining node, but the operation failed.

### Steps to Reproduce
It has been stuck at this step:(The following ip is fake, in fact I use the correct ip.)
```bash
root@ubuntu:/data/Zilliqa/join# curl ip.sb
1.2.3.4
root@ubuntu:/data/Zilliqa/join# ./launch_docker.sh 
Assign a name to your container (default: zilliqa): 
Enter your IP address ('NAT' or *.*.*.*): 1.2.3.4
Enter your listening port (default: 33133): <br>

```

#### Expected
Can successfully synchronize the information of the main network node and mine.

#### Actual
Not running successfully and don't know the error message

#### Impact:
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

### Additional Details
* Versions: docker image v5.0.1
* Operating System: Ubuntu 18.04.3 LTS  
* Installed packages:  runs from docker
* Screenshots / Log Files: https://pastebin.com/qT2Nkp4A

**Comment by bb111189** [comment]
Is the last line of log?
```
[2019-09-24 01:56:47.571124] Downloaded persistence/txBlocks/000446.ldb suc
```

It seems to be the log is truncated and not complete.

**Comment by wshhz** [comment]
It looks like it's not complete, but this is all the content in the download.log.

**Comment by wshhz** [comment]
The size of the download.log file always stays at 28672 (28k).

**Comment by bb111189** [comment]
May I know the following:
```
Processer spec
Memory:
Disk size:
```

So far, many community has run it without any issue. So I was suspecting it may the node is below spec. 

Also have you make any modification to the code so far?

**Comment by wshhz** [comment]
My machine configuration is as follows:
CPU 8 core AND 16G memory,200G HDD.

I follow this document to operate:https://github.com/FireStack2018/Awesome-Zilliqa/blob/master/Documents/Mining/Zilliqa主网挖矿指南.md#基础要求
