### ISSUE TITLE
[BUG] Local RPC not working when ip set to 0.0.0.0

### ISSUE THREAD

**Issue by Swaggadan** [Zilliqa/Zilliqa#1909]
### Steps to Reproduce
Download https://forum.zilliqa.com/t/rpc-status-server-guide/596
Make a node, set <IP_TO_BIND> to 0.0.0.0 . Open port 4301
#### Expected
Executing `python miner_info.py epoch -p 4301` on the should give me epoch information.
#### Actual
When command is ran, no result is given. The execution just hangs.
#### Impact:
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

### Additional Details
* Versions: v4.5.0
* Operating System:  Ubuntu 16.04
* Installed packages:  
* Screenshots / Log Files:
![image](https://user-images.githubusercontent.com/137142/67145604-c650cb80-f250-11e9-95c4-efaac3e9bc90.png)
![image](https://user-images.githubusercontent.com/137142/67145610-d2d52400-f250-11e9-883f-bfac8856259a.png)

**Comment by Swaggadan** [comment]
Any Update on this? 
Below is a picture of my open ports, and a copy of my constants file
![image](https://user-images.githubusercontent.com/137142/73839994-9e7c7800-47ed-11ea-9642-be2e9a951853.png)

![image](https://user-images.githubusercontent.com/137142/73840044-b3590b80-47ed-11ea-86de-65f703660136.png)

**Comment by bb111189** [comment]
It is meant to only work for localhost. i.e 127.0.0.1
