### ISSUE TITLE
[BUG]Downloading persistence from S3 has failed

### ISSUE THREAD

**Issue by liuxh-go** [Zilliqa/Zilliqa#1939]
this is log:
[INFO][ 4994][19-11-26T09:13:30.500][libNode/Node.cpp:153][DownloadPersistenceF] END
[WARN][ 4994][19-11-26T09:13:30.500][liqa/Zilliqa.cpp:210][operator()          ] Downloading persistence from S3 has failed. Will try again!
[INFO][ 4994][19-11-26T09:13:40.500][libNode/Node.cpp:153][DownloadPersistenceF] BEG
[INFO][ 4994][19-11-26T09:13:40.501][ils/SysCommand.h:123][ExecuteCmdWithOutput] BEG
[INFO][ 4994][19-11-26T09:13:40.536][ils/SysCommand.h:123][ExecuteCmdWithOutput] END
[INFO][ 4994][19-11-26T09:13:40.536][libNode/Node.cpp:153][DownloadPersistenceF] END
[WARN][ 4994][19-11-26T09:13:40.536][liqa/Zilliqa.cpp:210][operator()          ] Downloading persistence from S3 has failed. Will try again!

**Comment by oggy95** [comment]
Have the same issue with the new setup node. Is the issue still exist?

**Comment by bb111189** [comment]
Usually, such an issue occurs when you are unable to connect to Amazon S3. Do you have any firewall rules that deny such a connection?
