### ISSUE TITLE
Should co-sig over block header be part of the consensus message?

### ISSUE THREAD

**Issue by ansnunez** [Zilliqa/Zilliqa#194]
This issue is with reference to my comments in pull request #192 

Basically, it has to do with the fact that our Consensus signature is over the entire message.
If the message is a block, then it is a bit strange that the block itself also contains the signature field.
A bit of chicken-and-egg situation.

Please refer to the PR for more details.

**Comment by bb111189** [comment]
@jiayaoqijia

**Comment by ansnunez** [comment]
One thing we can do is copy how IPsec protocol works, where some fields of a packet are zeroed out when doing crypto operations.

We can zero out the signature part of the block when it is the message of the consensus. Then we update the block with the actual signature after consensus is done. Signature bitmap will also have to be zeroed out and padded to expected length.

**Comment by ansnunez** [comment]
After quick discussion with @jiayaoqijia I think the way to go is to modify the consensus classes to let them know the length of the part of the message that should be co-signed. I’ve done just this in pull request #192 for the microblock co-sig and necessary changes to consensus. DS block is still unchanged and will continue to have the whole block co-signed during consensus.
