### ISSUE TITLE
RPC: supports GetBalance for new address type

### ISSUE THREAD

**Issue by islishude** [Zilliqa/Zilliqa#2031]
Get balance for new type address and failed

```sh
curl --location --request POST 'https://dev-api.zilliqa.com' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetBalance",
    "params": ["zil1nvrnhkw8zmxffp49n5t8cl4rm0ewt8v2xg2zgx"]
}'
```

```json
{
    "error": {
        "code": -8,
        "data": null,
        "message": "Address size not appropriate"
    },
    "id": "1",
    "jsonrpc": "2.0"
}
```

But get balance for legacy address type and returns ok.

```sh
curl --location --request POST 'https://dev-api.zilliqa.com' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetBalance",
    "params": ["9b073bd9c716cc9486a59d167c7ea3dbf2e59d8a"]
}'
```

```json
{
    "id": "1",
    "jsonrpc": "2.0",
    "result": {
        "balance": "300000000000000",
        "nonce": 0
    }
}
```

**Comment by bb111189** [comment]
For the address format, `bech32` address format is only used at the SDKs and wallets level. 

At the core protocol, it is still using base16 formatting. For more information, you can also check out https://github.com/Zilliqa/ZIP/blob/master/zips/zip-1.md

**Comment by islishude** [comment]
But why rpc server doesn't convert bech32 address to base16 address?

**Comment by bb111189** [comment]
rpc server is hosted directly at the node. As such, as the core protocol layer doesn't support bech32, hence, the rpc doesn't support. This said I think it is a good feature to have and will improve usability. I will talk to the rest of the team.

**Comment by islishude** [comment]
Ok,Thanks for your reply.
