### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lich666dead** [Zilliqa/Zilliqa#2033]
#### Impact:
- [ ] Critical
- [ ] High
- [ ] Medium
- [ ] Low

### Additional Details
* Versions:
* Operating System:   Linux ehsunz 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Installed packages:  `node v10.20.0`, `Brave Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)`
* Screenshots / Log Files: 
![image](https://user-images.githubusercontent.com/21293723/79064643-1e193e00-7c9a-11ea-8050-8f2961edc6ce.png)

```connection to 'wss://dev-ws.zilliqa.com/' failed: Error during WebSocket handshake: Unexpected response code: 404```

**Comment by ansnunez** [comment]
Hi @lich666dead thanks for reporting this. We recently upgraded the public testnet and failed to set up the websocket service properly. It should be working fine now.

**Comment by lich666dead** [comment]
Thanks for you))
