### ISSUE TITLE
Hi,How can I join the IP white list?

### ISSUE THREAD

**Issue by islishude** [Zilliqa/Zilliqa#2082]
> As seed nodes do not draw data directly from lookup or shard nodes, it is necessary for exchanges to be whitelisted by Zilliqa in order to receive data broadcasts about the blockchain and its state. This requires a static, public IP address with minimally two open ports (inbound and outbound) at which it can be reached.  https://dev.zilliqa.com/docs/en/exchange-getting-started

**Comment by bb111189** [comment]
Hi. Do you have any specific purpose for running a seed node?

**Comment by islishude** [comment]
as exchange

**Comment by jingniao** [comment]
我们需要搭建一个节点作为钱包的后端，节点应该怎么搭建？
