### ISSUE TITLE
myaddr.txt for mining setup

### ISSUE THREAD

**Issue by nxy** [Zilliqa/Zilliqa#2093]
https://github.com/Zilliqa/Zilliqa/wiki/Mining#mining-with-docker-remotely

Step 12 mentions "myaddr.txt"

Am I supposed to modify the address inside "myaddr.txt" and replace with my "zil***" address? There was no step that mentioned modifying it.

The address I found inside "myaddr.txt" was not found on https://viewblock.io/zilliqa

**Comment by bb111189** [comment]
nope. At the core protocol, it is not using bec32 format. It will be in base16. When searching in viewblock using base16 address, do ensure there is `0x` in front of the address

**Comment by nxy** [comment]
Oh! Thanks
