### ISSUE TITLE
Mining node running but search for address not found

### ISSUE THREAD

**Issue by x-koin** [Zilliqa/Zilliqa#2100]
Hi there,

I have a running a Zilliqa miner but when I search for my address in https://viewblock.io/zilliqa I get "Address not found". It's been running for almost 24 hours...

Address is 
5e7de73cfba544593103b72476be16283069eb0b

Regards
Antony

**Comment by bb111189** [comment]
This is your address. https://viewblock.io/zilliqa/address/zil1te77w08m54z9jvgrkuj8d0sk9qcxn6ct0v9war

You will need to append `0x` infront of your address when searching in viewblock for base16 address format.
