### ISSUE TITLE
Mining - Address not showing up on viewblock.io

### ISSUE THREAD

**Issue by xcpdq** [Zilliqa/Zilliqa#2105]
Hello,

I am not sure what I am doing wrong but it seems I can't view any information about my address on viewblock.io/zilliqa. Nothing shows ("No result found" is the message). Does this mean I'm not mining? I can provide logs if needed. Please advise.

Thanks!

**Comment by ansnunez** [comment]
Hi @xcpdq please see if this [resolved issue](https://github.com/Zilliqa/Zilliqa/issues/2100) answers your question.
