### ISSUE TITLE
Broken link to Zilliqa mining forum

### ISSUE THREAD

**Issue by x-koin** [Zilliqa/Zilliqa#2133]
Hi there,

Your Wiki page links to the following url which comes up as "server IP address cannot be found".
Looks like it might be a DNS issue?
https://forum.zilliqa.com/c/Mining

The error is in the "Discussion Channels" section at the very bottom of this page: https://github.com/Zilliqa/Zilliqa/wiki/Mining#general-information

regards
Antony

**Comment by bb111189** [comment]
Thanks. We have depreciated our forum. I have updated the link.
