### ISSUE TITLE
Zilliqa Mining Error From Docker

### ISSUE THREAD

**Issue by antmikinka** [Zilliqa/Zilliqa#2138]
Hi guys, I followed the guide on how to start mining with docker locally. However I have not been able to mine because of this error. Any idea on how to fix it? I deleted the join file and just re-setup and unfortunately I'm still getting the error.  I followed this guide on my MacBook a couple months ago worked fine (didn't have a pc at the time). Any ideas or advice would be appreciated thank you.

**System Info**
Ubuntu 20.04
Nvidia 1650
Ryzen 5 3600

![unnamed](https://user-images.githubusercontent.com/67480807/86522444-d2ef7100-be2b-11ea-8cba-8dedc4ac5a9c.jpg)

**Comment by ansnunez** [comment]
Hi @antmikinka in the prompt "Assign a name to your container" you can indicate a new name other than "zilliqa" (e.g., "zilliqa2").
If that works, you can then also consider cleaning up your previous runs by doing `docker stop zilliqa` and `docker rm zilliqa`.
