### ISSUE TITLE
[Need Help] I'm wallet developer, need setup node for rpc(seed node)

### ISSUE THREAD

**Issue by jingniao** [Zilliqa/Zilliqa#2191]
use [exchange-getting-started](https://dev.zilliqa.com/docs/exchanges/exchange-getting-started) document and use docker to start 
after `./launch_docker.sh'
log show download from s3 success
**but not connect to other peers**
**zilliqa not sync to new block**

**Comment by ansnunez** [comment]
Closing this issue since author is already in touch by email

**Comment by Jodragon** [comment]
> 

I also encountered this problem, how should I solve it?
