### ISSUE TITLE
[BUG] Incorrect GetPendingTxn 'info' message when TX is not confirmed

### ISSUE THREAD

**Issue by rockacola** [Zilliqa/Zilliqa#2263]
### Issue 

`GetPendingTxn` returns `Txn already processed and confirmed` despite it's not yet confirmed.

### Steps to Reproduce

Request sent via console right after a success transaction:

```
$ curl -d '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetPendingTxn",
    "params": ["0xd1e9ff5b824b3cbc6892f0566c63cefdb097cc82c5bc64a848255c3d481608a1"]
}' -H "Content-Type: application/json" -X POST "https://dev-api.zilliqa.com/"

{"id":"1","jsonrpc":"2.0","result":{"code":0,"confirmed":false,"pending": false,"info":"Txn was already processed and confirmed"}}
```

#### Expected

I've expected to receive some kind of status message that TX is in the pool but not yet confirmed.

#### Actual

False positive message incorrectly indicates that the TX is already confirmed.

#### Impact:
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

### Additional Details
* Versions:
* Operating System:   
* Installed packages:  
* Screenshots / Log Files:

**Comment by rockacola** [comment]
I've only tested against the Testnet only and this said concern is not verified against the Mainnet.

**Comment by KaustubhShamshery** [comment]
This txn is indeed confirmed. Remove the 0x from the query.

```
curl -d '{
>     "id": "1",
>     "jsonrpc": "2.0",
>     "method": "GetPendingTxn",
>     "params": ["0xd1e9ff5b824b3cbc6892f0566c63cefdb097cc82c5bc64a848255c3d481608a1"]
> }' -H "Content-Type: application/json" -X POST "https://dev-api.zilliqa.com/"
{"error":{"code":-8,"data":null,"message":"Txn Hash size not appropriate"},"id":"1","jsonrpc":"2.0"}
```


```
cu
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetPendingTxn",
    "params": ["d1e9ff5b824b3cbc6892f0566c63cefdb097cc82c5bc64a848255c3d481608a1"]
}' -H "Content-Type: application/json" -X POST "https://dev-api.zilliqa.com/"
{"id":"1","jsonrpc":"2.0","result":{"code":0,"confirmed":true}}

```

**Comment by KaustubhShamshery** [comment]
The "info" field has been removed in this version. Can u give us more detail?

**Comment by rockacola** [comment]
For start, thanks for looking into this @KaustubhShamshery!

In my failed attempt to reduce dependencies to reproduce this issue, I've convert the `zilliqa-js` usages to `cURL` without testing (thought it was produce the same response payload).

Now after reverifying multiple times, I able to deduct that the issue is with the `zilliqa-js`, not JSON-RPC API itself.

Sorry for the confusion. I'll close this ticket and create a new issue in `Zilliqa-JavaScript-Library` repo.
