### ISSUE TITLE
CTest parallel build failed due to shared resource between test cases

### ISSUE THREAD

**Issue by Gnnng** [Zilliqa/Zilliqa#236]
See travis log: https://travis-ci.org/Zilliqa/Zilliqa/jobs/366715598

Once fixed, 0f3612157b5802afd32dec8e4ff4b641e9b04867 can be enabled again

**Comment by digiront** [comment]
What was the issue? Test db?

**Comment by Gnnng** [comment]
Seems that two or more test cases are having a race condition on the leveldb persistent storage. Could be fixed by using separate paths for persistent storage.

**Comment by Gnnng** [comment]
The testcase ReadBlock will fail when being run firstly after the cmake build, which indicates that it may depend on other unit tests that generate persistent storage for it. This violates the purpose of **unit testing** where each test case should be independent.
```
❯ ctest -R ReadBlock -VV
UpdateCTestConfiguration  from :/Users/Gnnng/workspace/Zilliqa/feature_build/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/Gnnng/workspace/Zilliqa/feature_build/build/DartConfiguration.tcl
Test project /Users/Gnnng/workspace/Zilliqa/feature_build/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 18
    Start 18: ReadBlock

18: Test command: /Users/Gnnng/workspace/Zilliqa/feature_build/build/tests/Persistence/ReadBlock
18: Test timeout computed to be: 9.99988e+06
18: Running 1 test case...
18: [TID 11544767][03:51:24][test_method         ] BEGIN
18: unknown location:0: fatal error: in "persistencetest/testBlockStorage": memory access violation at address: 0x00000110: no mapping at fault address
18: ../../../tests/Persistence/ReadBlock.cpp:32: last checkpoint: "testBlockStorage" test entry
18:
18: *** 1 failure is detected in the test module "persistencetest"
1/1 Test #18: ReadBlock ........................***Failed    0.04 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.05 sec

The following tests FAILED:
	 18 - ReadBlock (Failed)
Errors while running CTest
```

**Solution:**

Let ReadBlock generates the persistent storage for itself before the testing logic.

**Comment by satoshi101** [comment]
`testBlockStorage` was likely a starting point during development. Now it's part of `BOOST_AUTO_TEST_CASE(testBlockStorage)` in `Test_DSPersistence.cpp` and can safely be deleted.
