### ISSUE TITLE
Does the Zilliqa client work on WSL?

### ISSUE THREAD

**Issue by realuser** [Zilliqa/Zilliqa#2392]
**Is your feature request related to a problem? Please describe.**

Will the Zilliqa client work on windows via [WSL (Windows Subsystem for Linux)](https://docs.microsoft.com/en-us/windows/wsl/), either version 1 or 2?

**Describe the solution you'd like**

Zilliqa client to work on WSL

**Comment by bb111189** [comment]
It should be able to be compiled on WSL Ubuntu 18.04
