### ISSUE TITLE
Request for troubleshooting or unfreezing ZIL

### ISSUE THREAD

**Issue by DZIANIS809** [Zilliqa/Zilliqa#2435]
Hello! I have not been using my ZIL for a long time, now I want to exchange the ZIL, but I cannot withdraw them from the Wallet, it is written that the address does not fit !!! Previously my contracts were 0x18e36985a0 ....... but now they start zil1 ....... Can you help?### Issue 

#### Impact:
- [ ] Critical
- [x] High
- [ ] Medium
- [ ] Low

### Additional Details
* Versions:
* Operating System:   
* Installed packages:  
* Screenshots / Log Files:

**Comment by bb111189** [comment]
Please refer to https://blog.zilliqa.com/zilliqa-token-swap-recovery-plans-for-unswapped-erc-20-interim-zil-5220afa4a52f#:~:text=On%2015%20February%202020%2C%20Zilliqa,transitioning%20into%20its%20native%20platform.&text=~98.3%25%20of%20the%2012.6%20billion%20tokens%20were%20successfully%20swapped
