### ISSUE TITLE
5 days running but still no rewards at the address

### ISSUE THREAD

**Issue by n3bojs4** [Zilliqa/Zilliqa#2442]
Hello,

I am running the docker container : zilliqa/zilliqa:v7.1.0
No issues in the logs, still no rewards after 5 days of mining (checked at https://viewblock.io/zilliqa/ ).
Is there any explanation ?

Thanks for your reply.

**Comment by bb111189** [comment]
What is your specs of your mining rig?

The difficulty rate for nodes to solo mine and join the network is rather high at the moment. It is likely to be a couple of dozen of relative new GPUs.

I will recommend you trying out the existing mining pool if you do not have the required resources for solo mining. Most mining pools have straightforward guide to get you started. 
https://miningpoolstats.stream/zilliqa

**Comment by n3bojs4** [comment]
ok thanks for your quick reply.
I'll take a look at it and stop the process for now, it's waste of time, a good point should be to write it on the documentation.
I saw this question on the internet with no real good answer, and i think people like me left the project for that.

**Comment by bb111189** [comment]
Thanks for your feedback. We will add a note to the dev portal. Will be closing this issue for now
