### ISSUE TITLE
[BUG] Bad private key

### ISSUE THREAD

**Issue by Ryusmay** [Zilliqa/Zilliqa#2490]
Hello. In the zilpay mobile wallet, it was possible to generate an address to the wallet with an incorrect private key. After my submission, the bug has been fixed. The problem is that I have put some of my Zils and Gzils into this wallet and I can't get them back now. Is it possible to get my money back or is it gone forever? I note that it is due to an error that allowed to generate a wallet with an incorrect private key, which makes it impossible to transfer coins to a different address

**Comment by bb111189** [comment]
Do reach out to ZilPay team 

Closing this issue as this issue is not a core protocol issue

**Comment by Taupik002** [comment]
hi zilpay team, why every time my transaction always fails, the description of the failure is bad private key, is there a solution for me?
