### ISSUE TITLE
[BUG] GetTransactionStatus API not supported

### ISSUE THREAD

**Issue by vae520283995** [Zilliqa/Zilliqa#2494]
v7.2.0
curl -d '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetTransactionStatus",
    "params": ["1bb178b023f816e950d862f6505cd79a32bb97e71fd78441cbc3486940a2e1b7"]
}' -H "Content-Type: application/json" -X POST "http://127.0.0.1:4201"
{"error":{"code":-20,"data":null,"message":"API not supported"},"id":"1","jsonrpc":"2.0"}

The local seed node does not work.
But the endpoint https://api.zilliqa.com/ is ok

**Comment by bb111189** [comment]
This API uses an off-chain database to track and is only available in the public API endpoint. It will not be available on private endpoint
