### ISSUE TITLE
Any User friendly mining Software for Linux and Windows to mine Zilliqa directly on a pool

### ISSUE THREAD

**Issue by developeralgo8888** [Zilliqa/Zilliqa#2501]
i am new to Zilliqa . Any User friendly mining Software for Linux and Windows to mine  Zilliqa directly on a pool ? it is really confusing and annoying to get info on Zilliqa Miner  that doesn't have those insane dev fees ? what is the current miner version ? is it 0.4.2 or 7.2  .  Lacking proper instructions and extremely disorganized.

**Comment by bb111189** [comment]
If you do not want to join a mining pool, it means you need to set up your own node, mining proxy, and use mining software that supports ETHash algorithm However, to join a shard node, with current difficulty rate, it is likely you will need more than 300 modern GPU.  

We only provide the instruction and using the default mining software by us. For other mining software out there that you can check the respective mining software webpage. eg. claymore, phoenix, ethermine, lolminer etc. 

https://dev.zilliqa.com/docs/miners/mining-getting-started/
