### ISSUE TITLE
[BUG] PendingTxns throwing error on dev api-call

### ISSUE THREAD

**Issue by tburrieza** [Zilliqa/Zilliqa#2514]
### Issue 

Hi, I was using the Zilliqa Developer API (`https://dev-api.zilliqa.com`) and after calling a method with a JSONRPC call I'm getting an exception as a response.

The error is answered by Zilliqa's Dev API when calling the method `GetPendingTxn`.

This error cannot be reproduced on mainnet. The result on this network is what an user is expecting but on Dev API is quite different.

As I saw on [Zilliqa's Developer Documentation](https://dev.zilliqa.com/docs/apis/api-transaction-get-pending-tx) the JSONRPC Method `GetPendingTxn` **is supported both on Mainnet API** (`https://api.zilliqa.com`) **and on Testnet API** (`https://dev-api.zilliqa.com`).

The exact `unexpected` response is
```
{"error":{"code":-32601,"message":"METHOD_NOT_FOUND: The method being requested is not available on this server"},"id":"1","jsonrpc":"2.0"}
```
`when calling https://dev-api.zilliqa.com`

and on mainnet, the `expected` is response

```
{"id":"1","jsonrpc":"2.0","result":{"code":0,"confirmed":false,"pending":false}}
```

### Steps to Reproduce

1. Make a contract (what I'm doing) deployment con Testnet.
2. Get the Transaction Hash from the past step.
3. Make a JSONRPC Call to `https://dev-api.zilliqa.com` with the method `GetPendingTxn` and the Transaction Hash into `params`
4. See the result

#### Expected

It's expected to receive a result showing if the transaction is still pending or confirmed (like mainnet)

#### Actual
An error response is showed.
`{"error":{"code":-32601,"message":"METHOD_NOT_FOUND: The method being requested is not available on this server"},"id":"1","jsonrpc":"2.0"}`

#### Impact:
- [ ] Critical
- [x] High
- [ ] Medium
- [ ] Low

(marked High because it can delay development process from thrid parties working with Zilliqa Network or it can be introduced on mainnet)

### Additional Details
* Versions:
* Operating System:   
* Installed packages:  
* Screenshots / Log Files:

A screenshot making the JSONRPC Call with cURL

![image](https://user-images.githubusercontent.com/51381445/115100382-9ef4c080-9f12-11eb-93f6-c3ff3687f97d.png)
`API Call to https://dev-api.zilliqa.com with cURL and a JSONRPC Payload`

I surfed over the issues and have not found any describing this error. Apologies if it is duplicated.

**Comment by bb111189** [comment]
We recently released the following announcement on our discord and telegram dev channel. We will be removing this API with effect from v8.0.0. The current testnet has been upgraded to v8.0.0 as part of our release cycle process

```
Dear All,

In preparation for the next mainnet upgrade to the upcoming Zilliqa release (estimated mid April), please be aware of the following breaking changes:

1. Payment transaction fee will increase from 0.002 ZIL to 0.1 ZIL (assuming the default gas price value 1 is used).
  This is in accordance with Zilliqa Improvement Proposal (ZIP) #18, which passed governance vote earlier this month.
  Please refer to this link for more details: https://governance.zilliqa.com/#/gzil/proposal/QmcxZJ5x7o9tWRmjD73uopRno35iwJhydgTTCbHsS1AFUt
  Note that smart contract transaction fees remained unchanged.
  To anticipate this change, developers and exchanges will need to call CreateTransaction with "gasLimit" set to "50" instead of "1".
  Note that you may choose to make this change as early as today, as you will NOT be charged the new fee rate until after the mainnet upgrade next month.

2. The API GetPendingTxn - used to check for the status of an unconfirmed transaction - will be deprecated and removed by the next mainnet upgrade.
  We recommend developers and exchanges to switch to the alternative API GetTransactionStatus.
  Please refer to the API documentation for more details: https://dev.zilliqa.com/docs/apis/api-transaction-get-transaction-status

Thank you for your continued support!
```

**Comment by tburrieza** [comment]
Hi @bb111189 ! Thank you for the information provided!

I will use the alternative mentioned on the announcement that you've bringed here.
I've just entered Zilliqa's Discord Server to be up to date about following changes.

Regards 🙌
