### ISSUE TITLE
oldest leader submit pow2 soln but not accepted

### ISSUE THREAD

**Issue by bb111189** [Zilliqa/Zilliqa#252]
1. Oldest ds backup get kick out of the ds committee
2. Oldest ds backup compute pow2 and  submit soln to ds committee to rejoin the network
3. Oldest ds backup submit the pow2 (before ds leader and ds backup) changes state. 
4. Oldest ds backup submission get dropped as a result. It failed to join the network. 

Soln:
When receiving pow2 solution, if the state is incorrect. It will set a conditional variable with timeout to wait for state transition before processing the pow2 solution.

Upon state transition, ds leader or backup should use notify_all() to notify all thread to start processing the pow2 submission

**Comment by ckyang** [comment]
Done in https://github.com/Zilliqa/Zilliqa/pull/301
