### ISSUE TITLE
[FEATURE REQUEST]Can current Zilliqa support complex smart contract (i.e., a contract calls other contracts during its execution)?

### ISSUE THREAD

**Issue by qqbrother** [Zilliqa/Zilliqa#2559]
I have read some reference about the Zilliqa, and find that the execution of a smart contract is completed in a specific shard. In this case, if a smart contract *A* residing shard 1 needs to call and modify another contract *B* residing another shard 2, which shard is responsible to update the contract *B*?

**Comment by bb111189** [comment]
Then the smart contract transaction is considered a Type 3 smart contract transaction and will be processed by the DS committee

https://blog.zilliqa.com/provisioning-sharding-for-smart-contracts-a-design-for-zilliqa-cd8d012ee735
