### ISSUE TITLE
[BUG] Zilliqa testnet wallet not working

### ISSUE THREAD

**Issue by hamxabaig** [Zilliqa/Zilliqa#2626]
After creating the wallet, api throws error "Account not created". I can't send any test zils to my wallet as well.

<img width="1440" alt="Screen Shot 2021-06-23 at 4 12 41 PM" src="https://user-images.githubusercontent.com/12872177/123087323-db2a2d00-d43d-11eb-91b9-ee930b2fc93d.png">

**Comment by bb111189** [comment]
As the account has not interacted with blockchain yet, it will still be seen as the account is not created. This is a valid keypair
There is no issue and you can use this on the testnet.

**Comment by hamxabaig** [comment]
Yes i know that, but the testnet faucet doesn't work as well therefore there is no way to interact with the chain. It doesn't send any test zil to this account.
