### ISSUE TITLE
Add Bitlive.pro to exchange list

### ISSUE THREAD

**Issue by Zilliqa-Bitlive** [Zilliqa/Zilliqa#2630]
Hello
Our non-custodial exchange service provides our customers with the ability to exchange cryptocurrencies in over 90,000 exchange pairs.

Our service allows customers to exchange Zilliqa cryptocurrency to more than 250 cryptocurrencies, we provide the most favorable exchange rate, and minimal exchange fees.

We would like to suggest that you place a mention for Zilliqa cryptocurrency holders on your website in the exchange partners section about our service.

Installing our service in your section exchange partners will give Zilliqa holders the opportunity to make instant exchange at favorable exchange rates with minimal commissions, without registration.

The advantage of our service: Non-custodial exchange, Best exchange rate, Round the clock support, Exchange without registration, User-friendly interface.

If anything needs to be provided to place our service in your partners section, please contact us and we will provide everything you need.

Official website https://bitlive.pro/
Regards, Bitlive.pro Affiliate Department

**Comment by bb111189** [comment]
Wrong place and your website is labeled as scam by TrendMicro 

![image](https://user-images.githubusercontent.com/4401980/123537020-03789b00-d760-11eb-8a60-b7aecd11b0fa.png)
