### ISSUE TITLE
Staked seed node dashboard for Grafana

### ISSUE THREAD

**Issue by big-bag** [Zilliqa/Zilliqa#2730]
I deployed the Zilliqa Staked Seed Node in Testnet by instruction: https://dev.zilliqa.com/docs/staking/phase1/ssn-operator/staking-ssn-setup/

And I have questions:
1. does the Zilliqa Staked Seed Node return metrics to upload them to Prometheus?
2. if yes, how can I get these metrics?
3. if yes, do you have a Grafana dashboard for these metrics?

**Comment by bb111189** [comment]
Node does not return metrics.

**Comment by big-bag** [comment]
Thanks!
