### ISSUE TITLE
[BUG] Downloads from AWS gives 404 errors

### ISSUE THREAD

**Issue by da-tai** [Zilliqa/Zilliqa#2731]
### Issue 

When just starting a node, it attempts to downloads files from AWS. This isn't always successful leading to a bad node that continuously restarts because it's attempting to download the data.

### Steps to Reproduce

Start a node and monitor py_download_incr_DB.log

#### Expected
Expected to download all files without 404 errors

#### Actual
Files fail to download because the file doesn't exist.

#### Impact:
- [ ] Critical
- [x] High
- [ ] Medium
- [ ] Low

### Additional Details
* Versions: zilliqa:v8.1.0
* Operating System: Ubuntu 21.01
* Installed packages:  
* Screenshots / Log Files:  [py_download_incr_DB.log](https://github.com/Zilliqa/Zilliqa/files/7236506/py_download_incr_DB.log)

**Comment by Snuff** [comment]
I've got the same issue sometimes. I think the impact is high because it seems AWS bans IP of the node for some time so. When you host a node on a VPS with billing on monthly basis it's very difficult to change the IP, so your hardware is just waiting for unban.

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
