### ISSUE TITLE
[BUG] Can't install, fatal error: bits/signum.h: No such file or directory leading to gmake: *** [Makefile...all] Error 2

### ISSUE THREAD

**Issue by Lemanr-ops** [Zilliqa/Zilliqa#2752]
### Issue 
Unable to install Zilliqa using Fedora by following "Build from Source" instructions. 
### Steps to Reproduce
I followed instructions starting from:
download the lastest stable Zilliqa source code
```
$ git clone https://github.com/Zilliqa/Zilliqa.git
$ cd Zilliqa && git checkout tags/v8.1.0
# build Zilliqa binary
$ ./build.sh
```

Errors had occurred to install some dependencies as the user I'm installing for doesn't have sudo access. To resolve I'd log into root, install missing dependency, exit back to user then use ./build.sh & repeat.

Unfortunately I've installed just about everything related to mongoc but I am still receiving error in command line ending with
```
-- Building and installing cryptoutils
-- Building and installing mongo driver. This could take longer
CMake Error at cmake/InstallMongo.cmake:55 (message):
  Error when building and installing mongoc, see more in log
  /home/ryanl/Desktop/Applications/Zilliqa/Zilliqa/build/src/depends/install_mongo.log
Call Stack (most recent call first):
  CMakeLists.txt:48 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ryanl/Desktop/Applications/Zilliqa/Zilliqa/build/CMakeFiles/CMakeOutput.log".

```
Following "install_mongo.log" I see at the bottom
```
Consolidate compiler generated dependencies of target test-libmongoc
/home/ryanl/Desktop/Applications/Zilliqa/Zilliqa/src/depends/mongo-c-driver/src/libmongoc/tests/test-mongoc-cache.c:24:10: fatal error: bits/signum.h: No such file or directory
   24 | #include <bits/signum.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/libmongoc/CMakeFiles/test-mongoc-cache.dir/build.make:76: src/libmongoc/CMakeFiles/test-mongoc-cache.dir/tests/test-mongoc-cache.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1698: src/libmongoc/CMakeFiles/test-mongoc-cache.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 88%] Linking C executable example-collection-watch
[ 88%] Built target test-libmongoc
[ 88%] Linking C executable example-create-indexes
[ 88%] Built target example-collection-watch
[ 88%] Built target example-create-indexes
gmake: *** [Makefile:156: all] Error 2

```
The link to the whole file is here:
[install_mongo.log](https://github.com/Zilliqa/Zilliqa/files/7541497/install_mongo.log)

"build/CMakeFiles/CMakeOutput.log" is in the link below
[CMakeOutput.log](https://github.com/Zilliqa/Zilliqa/files/7541468/CMakeOutput.log)

#### Expected
The next step of the installation process
#### Actual
The error messages stated above
### Additional Details
* Versions: v8.1.0
* Operating System:  Fedora 35
* Installed packages:  
```
bash-5.1# dnf list *libmongo*
Last metadata expiration check: 1:16:25 ago on Mon 15 Nov 2021 02:27:00 PM EST.
Installed Packages
libmongocrypt.x86_64                           1.3.0-1.fc35                    @updates
libmongocrypt-devel.x86_64                     1.3.0-1.fc35                    @updates

bash-5.1# dnf list *mongo-c*
Last metadata expiration check: 1:16:39 ago on Mon 15 Nov 2021 02:27:00 PM EST.
Installed Packages
mongo-c-driver.x86_64                              1.19.2-1.fc35               @updates
mongo-c-driver-devel.x86_64                        1.19.2-1.fc35               @updates
mongo-c-driver-libs.x86_64                         1.19.2-1.fc35               @updates
mongo-cxx-driver.x86_64                            3.6.5-1.fc35                @fedora 
mongo-cxx-driver-bsoncxx.x86_64                    3.6.5-1.fc35                @fedora 
mongo-cxx-driver-bsoncxx-devel.x86_64              3.6.5-1.fc35                @fedora 
mongo-cxx-driver-devel.x86_64                      3.6.5-1.fc35                @fedora 
bash-5.1# 
```

**Comment by Lemanr-ops** [comment]
I gave user sudo privileges in the hopes it'll prompt to install some missing dependency however I got the same results then changed sudo privileges back to the way I had it.

**Comment by Lemanr-ops** [comment]
So I'm going to learn about using docker & possibly moby for my work. When I get that all running I'll use them to do my work with Zilliqa.
However MANY people use non-debian based distros so I highly encourage the dev team here to make this available for other non-debian based distros.

**Comment by jubnzv** [comment]
Recently I came around the same bug while building Zilliqa on Arch.

I found that `bits/signum.h` [was removed](https://jira.mongodb.org/browse/CDRIVER-3802): https://github.com/mongodb/mongo-c-driver/commit/1209d5202a59e61c499a7c686abcf962f48b109f.

So, the simplest solution was manually applying the patch from the commit above in the installation directory.
