### ISSUE TITLE
Scilla language reference guide

### ISSUE THREAD

**Issue by pressplay21** [Zilliqa/Zilliqa#277]
Where can I find "how to get started" with smart contract development?

**Comment by bb111189** [comment]
More information will be released in the future. Stay tune to our blog/announcement channel. 
Blog: https://blog.zilliqa.com/
Slack: https://invite.zilliqa.com/
Telegram announcement channel: https://t.me/zilliqa

To find out more about Scilla, you can refer to https://arxiv.org/pdf/1801.00687.pdf
