### ISSUE TITLE
Fedora support

### ISSUE THREAD

**Issue by 0x34d** [Zilliqa/Zilliqa#2795]
**Hey, Zilliqa**
1. Dose dev update Core compiles support in Fedora. 
-> Not everyone uses ubuntu.
2. I Don't wanna to compile depends.
-> it would be really great if core supported direct use of libraries rather than compile them and use them...

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
