### ISSUE TITLE
Running test sample with IO error

### ISSUE THREAD

**Issue by kevinhand** [Zilliqa/Zilliqa#283]
$ cd build && ./tests/Node/test_node_simple.sh
net.core.somaxconn = 102400
net.core.netdev_max_backlog = 65536
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_rmem = 65536 873800 1534217728
net.ipv4.tcp_wmem = 65536 873800 1534217728
net.ipv4.tcp_mem = 65536 873800 1534217728
zilliqa: no process found
sendtxn: no process found
Traceback (most recent call last):
  File "tests/Zilliqa/test_zilliqa_local.py", line 256, in <module>
    main()
  File "tests/Zilliqa/test_zilliqa_local.py", line 58, in main
    print_usage() if (numargs != 3) else run_setup(numnodes=int(sys.argv[2]), printnodes=True)
  File "tests/Zilliqa/test_zilliqa_local.py", line 108, in run_setup
    shutil.copyfile('./build/tests/Zilliqa/zilliqa', testsubdir + '/zilliqa')
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: './build/tests/Zilliqa/zilliqa'
Traceback (most recent call last):
  File "tests/Zilliqa/test_zilliqa_local.py", line 256, in <module>
    main()
  File "tests/Zilliqa/test_zilliqa_local.py", line 60, in main
    print_usage() if (numargs != 3) else run_start(numdsnodes=int(sys.argv[2]))
  File "tests/Zilliqa/test_zilliqa_local.py", line 132, in run_start
    process = Popen(["./build/tests/Zilliqa/genkeypair"], stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

The error resolved after making following change in test_zilliqa_local.py line 108-110, line 132

shutil.copyfile('./build/tests/Zilliqa/zilliqa', testsubdir + '/zilliqa')
shutil.copyfile('./build/tests/Zilliqa/sendcmd', testsubdir + '/sendcmd')
shutil.copyfile('./build/tests/Zilliqa/sendtxn', testsubdir + '/sendtxn')
                         to
shutil.copyfile('./tests/Zilliqa/zilliqa', testsubdir + '/zilliqa')
shutil.copyfile('./tests/Zilliqa/sendcmd', testsubdir + '/sendcmd')
shutil.copyfile('./tests/Zilliqa/sendtxn', testsubdir + '/sendtxn')

process = Popen(["./build/tests/Zilliqa/genkeypair"], stdout=PIPE)
                        to
process = Popen(["./tests/Zilliqa/genkeypair"], stdout=PIPE)

**Comment by KaustubhShamshery** [comment]
I suggest run ./build.sh from the root directory and then see if build/tests/Zilliqa/zilliqa is present or not. It should be present

**Comment by kevinhand** [comment]
Hi, the building is fine with no error. The problem is on running test. The path specified mismatch. I have given the error code location. Not sure why other people do not have this error.

**Comment by KaustubhShamshery** [comment]
just check if build/tests/Zilliqa/zilliqa is present or not. It should be preset. Otherwise re-build and try

**Comment by KaustubhShamshery** [comment]
yes the readme must be updated. The test must be run from root folder not build/

**Comment by bb111189** [comment]
PR #286  fixes this issue
