### ISSUE TITLE
Replace asserts with appropriate error handling code

### ISSUE THREAD

**Issue by ansnunez** [Zilliqa/Zilliqa#304]
Need to make sure we aren’t skipping some necessary checks because of assert code, which only works in debug mode

**Comment by ckyang** [comment]
Currently g3log will automatically crash the program for FATAL message.
Thus the proposal of this issue should be:

assert(condition);
->
LOG_GENERAL(FATAL, "assertion failed (" << __FILE__ << ":" << __LINE__ << ": " << __FUNCTION__ << ")" << IfThereIsCustomMsg);

**Comment by ansnunez** [comment]
Interesting, didn't know.  Yes, we can use FATAL, and on the other hand I think some existing asserts may not necessary need to be at FATAL level (maybe just WARNING).

**Comment by ckyang** [comment]
Done in https://github.com/Zilliqa/Zilliqa/pull/314
