### ISSUE TITLE
Don’t use sizeof on Boost types uint128_t and uint256_t

### ISSUE THREAD

**Issue by ansnunez** [Zilliqa/Zilliqa#305]
Macros UINT256_SIZE (=32) and UINT128_SIZE (=16) are defined in Constants.h because these types are not native types and sizeof(uint256_t) actually returns 48 instead of 32.

I noticed there is some code in DirectoryService that uses sizeof(uint256_t) and this should be corrected.

**Comment by ckyang** [comment]
sizeof(uint256_t):
libNode/PoW1Processing.cpp
libNode/ShardingInfoProcessing.cpp
libNode/FinalBlockProcessing.cpp
libNode/MicroBlockProcessing.cpp
libDirectoryService/PoW1Processing.cpp
libDirectoryService/ShardingPostProcessing.cpp
libDirectoryService/PoW2Processing.cpp
libDirectoryService/FinalBlockPostProcessing.cpp
libDirectoryService/DirectoryService.cpp
libDirectoryService
libDirectoryService

**Comment by ansnunez** [comment]
uint128 should also be corrected, just in case in the future sizeof(uint128_t) will no longer be 16 after a Boost lib update

**Comment by ckyang** [comment]
@ansnunez So far I don't see sizeof(uint128_t) been used in any place of the code. Thanks for your reminder.

**Comment by ckyang** [comment]
Done in https://github.com/Zilliqa/Zilliqa/pull/307
