### ISSUE TITLE
Investigate missing code coverage in src/libDirectoryService and src/libNode

### ISSUE THREAD

**Issue by sharwell** [Zilliqa/Zilliqa#313]
See https://github.com/Zilliqa/Zilliqa/pull/58#issuecomment-393011389.

These directories may not be covered by tests running automatically during Travis builds. If the tests exist and are running, it's not clear why coverage data isn't appearing. If the tests exist and aren't running, they should be added to the Travis sequence that runs during `ctest`. Here is my original explanation for the common causes:

> The files are not intentionally excluded. If you expected the code to be covered by one or more specific tests, the first step is making sure that test is running during the Travis builds. If the files are not covered by current tests, the first step is making sure one or more test classes exists which at least links against the libraries containing the source files. If there are no tests running which reference the library code, then the tools have no way of knowing the files exist for inclusion.

**Comment by ckyang** [comment]
If the tests don't exist, we should add more tests.
