### ISSUE TITLE
Add state root to final block composed at the last mini-epoch of every major epoch

### ISSUE THREAD

**Issue by sidutta** [Zilliqa/Zilliqa#32]
The DS committee doesn't have the txn bodies when composing final blocks usually. Since txn body sharing is asynchronous, there are no guarantees as to when the entire network can agree on a common account state. The current plan is to make the network synchronous every 2 hrs or so(at the last min epoch of every major epoch) at the cost of extra delays and refetches for missing txn bodies and add the state root to the final block composed then. After this epoch, the sharding structure will reshuffle.

**Comment by bb111189** [comment]
Closed. Implemented at PR #56
