### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by weimenglee** [Zilliqa/Zilliqa#3289]
### Issue 

When trying to subscribe to events fired by my smart contract using:

zilliqa.subscriptionBuilder.buildEventLogSubscriptions( 'wss://dev-ws.zilliqa.com',
      {addresses: [contractAddress],}

It returns the error "ws.ts:38 WebSocket connection to 'wss://dev-ws.zilliqa.com/' failed: ". 

#### Impact:
- [ ] Critical
- [x] High
- [ ] Medium
- [ ] Low

### Additional Details
* Versions:
* Operating System:   
* Installed packages:  
* Screenshots / Log Files:

**Comment by JamesHinshelwood** [comment]
Hi @weimenglee , we accidentally broke the websocket API in our testnet for a few days in December, sorry if this affected you. It should be fixed now.
