### ISSUE TITLE
Implement a feedback mechanism in the consensus protocol code

### ISSUE THREAD

**Issue by sidutta** [Zilliqa/Zilliqa#34]
Currently if the leader proposes some value and the other nodes don't agree, consensus fails(just stalls under current code). We need a way for the other nodes to communicate to the leader on why they don't agree with the value so that the leader can propose an adjusted value that will pass the super-majority test.

**Comment by ansnunez** [comment]
This is already addressed by the Consensus CommitFailure message. Closing the issue.
