### ISSUE TITLE
Array Size Type Compiler Error on ARM

### ISSUE THREAD

**Issue by riceke** [Zilliqa/Zilliqa#342]
Hello!

When compiling on an ARM platform (ASUS TinkerBoard with Armbian) the templated inline function 'charArrToHexStr' (in DataConversion.h) gives rise to an error due to mismatch between expected and actual array size type.

The compiler error goes away when changing the type of 'SIZE' to 'size_t' instead of 'long unsigned int'.

Perhaps it is better to use 'size_t' here as it seems to be the portable type used for array sizes.

Thanks!

**Comment by sniperpr** [comment]
yes,  armhf compile has error.
if arm64 to compile, is ok.

**Comment by bb111189** [comment]
Merged.
