### ISSUE TITLE
[FEATURE REQUEST] Support Clion

### ISSUE THREAD

**Issue by DinoStray** [Zilliqa/Zilliqa#3445]
I hope we can support Clion IDE.  
Now I can use build.sh successfully build code.  
But Clion open the project failed to find third libs

**Comment by Steve-White-UK** [comment]
Internally within the core team, we use a mixture of IDEs. Clion, Visual Studio Code we even have a few diehard emacs fans and some that love vi.

If you can supply more information as to the particular third-party library you think is missing one of us would be glad to assist we can. 

It would be helpful to know which operating system and version you are building on as well as the compiler version, and a pertinent sample of the build output showing the error, even a screenshot if it helps.

**Comment by DinoStray** [comment]
OS: ubuntu 22
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

```
- Python suffix: python310
-- Python Version: 310
-- Found Boost: /work/Zilliqa/cmake-build-debug/vcpkg_installed/x64-linux/include (found version "1.80.0") found components: python310 
-- LLVM extra tools NOT found (for clang format/tidy)
-- Configuring done
CMake Error at src/libRemoteStorageDB/CMakeLists.txt:4 (target_link_libraries):
  Target "RemoteStorageDB" links to:

    mongo::mongocxx_shared

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

**Comment by DinoStray** [comment]
If I use build.sh, all the pakage managed by vcpkg, installed at Zilliqa/build/vcpkg_installed. 
But I think cmake for Clion not find lib by this folder.  
But rebuild all pakage in  cmake-build-debug .

**Comment by Steve-White-UK** [comment]
we usually switch the clion build directory from cmake-build-debug to build in the clion settings for local development.

also ./build.sh style is quite useful for tidying up the code into the zilliqa style

if you have ninja, you can switch to ninja builds and use ./build.sh ninja and also change that in clion settings from Unix Makefile to Ninja.

be sure to clear the build dir before doing that as they are not compatible and will complain.

There is no right or wrong way, just each to his/her personal taste.

**Comment by DinoStray** [comment]
I use ./build.sh successfully,  but Clion failed.  
```
CMake Error at src/libRemoteStorageDB/CMakeLists.txt:4 (target_link_libraries):
  Target "RemoteStorageDB" links to:

    mongo::mongocxx_shared
```
I found the difference between ./cmake-build-debug and ./build folder.
in ./cmake-build-debug, there is no vcpkg_installed/x64-linux-dynamic folder.

**Comment by DinoStray** [comment]
CLion only build:
libgmock.a
libmongoc-static-1.0.a
libmongocxx-static.a

and build.sh only build
libmongoc-1.0.so
libmongoc-1.0.so.0
libmongoc-1.0.so.0.0.0
libmongocxx.so
libmongocxx.so.3.6.5
libmongocxx.so._noabi

**Comment by DinoStray** [comment]
I change 
target_link_libraries(RemoteStorageDB PRIVATE mongo::mongocxx_shared)
to
target_link_libraries(RemoteStorageDB PRIVATE mongo::mongocxx_static)

solved the problem

**Comment by DinoStray** [comment]
> CLion only build: libgmock.a libmongoc-static-1.0.a libmongocxx-static.a
> 
> and build.sh only build libmongoc-1.0.so libmongoc-1.0.so.0 libmongoc-1.0.so.0.0.0 libmongocxx.so libmongocxx.so.3.6.5 libmongocxx.so._noabi

@Steve-White-UK  I wonder why Clion not build dynamic lib?

**Comment by DinoStray** [comment]
I add -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic to my clion CMake Options.  
Then solved the problem
