### ISSUE TITLE
Fetch data from the seed nodes instead of the lookup node in the synchronization phase

### ISSUE THREAD

**Issue by sidutta** [Zilliqa/Zilliqa#37]
There are certain nodes that are built as lookup nodes. Such nodes do not participate in the consensus. They silently keep accepting and storing blocks and n/w information.

Currently, any new node joining the n/w synchronizes with the lookup node. Instead the lookup node should be sending a list of seed nodes. New or laggy nodes should synchronize with these seed nodes. Request a few and wait for responses from some, do some verification on the responses received etc.

**Comment by ansnunez** [comment]
This is now implemented
