### ISSUE TITLE
Make "unused" parameter as few as possible

### ISSUE THREAD

**Issue by ckyang** [Zilliqa/Zilliqa#370]
https://github.com/Zilliqa/Zilliqa/pull/365
After this PR, we already turn on -Wextra.
Then we should start to make "unused" parameter as few as possible, to simplify our code structure.

**Comment by rahultelegram** [comment]
good job

**Comment by ckyang** [comment]
Currently there still some compile flag inside (IS_LOOKUP_NODE), the -Wextra will report some "false alarm."
For example, bool Node::ProcessMicroblockConsensus([[gnu::unused]] const vector<unsigned char>& message,[[gnu::unused]] unsigned int offset, [[gnu::unused]] const Peer& from)
where "message" is indeed be used in this function but because it's inside the flag "IS_LOOKUP_NODE", thus the variable is reported as "unused."
Now we will skip this issue until someday the "IS_LOOKUP_NODE" is removed entirely from our code base.

**Comment by Gnnng** [comment]
> Currently there still some compile flag inside (IS_LOOKUP_NODE), the -Wextra will report some "false alarm."

I'm afraid this hardly can be called a "false alarm". The "unused" complaints are only coming from the non-lookup build and the compiler in this build cannot know that those variables will be used in the lookup build. 

The current way of adding `[[gnu::unused]]` attributes to those variables is just a workaround to at least suppress the warning coming from the non-lookup build.
