### ISSUE TITLE
关于ZIL在中国发展的建议

### ISSUE THREAD

**Issue by HunanChianLi** [Zilliqa/Zilliqa#372]
中国，是一个地大物博，人口众多的国家。也是一个财富发展极度不平衡，充满着对金钱的追求的国家。因此，区块链系统在中国的发展，其特性，仅仅只占很小很小一部分，更多的，还是相性，及便捷性。
        便捷性的第一点，是挖矿便捷。根据cnnic2016年的数据统计，中国网民使用手机上网的比例达到百分之九十。因此，若能提供一款可用手机挖矿的软件，植入到中国民众的手机中，相信对于zil的价格而言，会有一个巨大的飞跃。
        便捷性的第二点，是使用便捷。苹果手机的开发语言同样与安卓的开发语言不同，却能成为和安卓平台相互抗争的一大终端，使用便捷这个特性功不可没。因此，相对于其他的区块链项目，zil更需要不断完善自身的生态社区，打造一个集新闻，游戏，金融，生活，医疗甚至是职业发展于一体的综合性区块链社区，让拥有zil的用户享受到更周到，便捷的服务。
        便捷性的第三点，是宣传。要向更多的人区块链项目的人宣传自身的思想。这就需要摆脱以往的宣传模式，充分的和当地的新闻媒体，网络红人甚至是著名演员相结合，向其受众宣传我们自身的思想，吸引其加入到zil这个大家庭中。
       最后，建议注重尊重地域性的主权完整，zil真正需要发展起来，必须将根部深深的植入到每一个国家，而不是当漂浮在互联网上的幽灵，因此，要更加注重维护各个国家的主权完整，尊重各国相应的商业规则和国家法律。

**Comment by AmritKumar** [comment]
I don't think this is the right place to convey this message. So, closing it.
