### ISSUE TITLE
[BUG] can't transfer() fungible token through ERC20-bridge using Metamask

### ISSUE THREAD

**Issue by maxhiker** [Zilliqa/Zilliqa#3729]
It's not possible to transfer tokens using Metamask (and possibly other wallets) through the `ERC20isZRC2.sol` bridge contract.

The reason is that the method signatures are partially incompatible with the ERC20 standard.

Refer to the ERC20 standard as defined on https://ethereum.org/en/developers/docs/standards/tokens/erc-20/ :

```
function name() public view returns (string)
function symbol() public view returns (string)
function decimals() public view returns (uint8)
function totalSupply() public view returns (uint256)
function balanceOf(address _owner) public view returns (uint256 balance)
function transfer(address _to, uint256 _value) public returns (bool success)
function transferFrom(address _from, address _to, uint256 _value) public returns (bool success)
function approve(address _spender, uint256 _value) public returns (bool success)
function allowance(address _owner, address _spender) public view returns (uint256 remaining)
```

Compare the above with the implementation from https://github.com/Zilliqa/Zilliqa/blob/master/tests/EvmAcceptanceTests/contracts/ERC20isZRC2.sol :

```
function totalSupply() external view returns (uint128);
function balanceOf(address tokenOwner) external view returns (uint128);
function allowance(address tokenOwner, address spender) external view returns (uint128);
function approve(address tokenOwner, uint128 tokens) external returns (bool);
function transfer(address to, uint128 tokens) external returns (bool);
function transferFrom(address from, address to, uint128 tokens) external returns (bool);
```

The **uint** types are different. When Metamask creates transaction data for `eth_sendRawTransaction`, it assumes that the contract is ERC-20 compatible and thus creates function data / sighash accordingly:

```
const sighash = hre.ethers.utils.id("transfer(address,uint256)");
console.log(sighash.slice(0, 10)); // Outputs: 0xa9059cbb
```

Therefore, Zilliqa's EVM is unable to execute this function encoded in the raw transaction due to signature incompatibility.

**Comment by rrw-zilliqa** [comment]
Thanks! "Surely" this is just a matter of changing the ERC20 EVM contract to use the correct signature?

**Comment by rrw-zilliqa** [comment]
(and transferFrom, for that matter)

**Comment by rrw-zilliqa** [comment]
Looks like they were - changing to uint256 passes the tests, so I think that was just a mistake on our part - sorry! - I'll fix it (in a nicer way than force-casting everything!). Just change to uint256 and it should work?

**Comment by rrw-zilliqa** [comment]
Thank you! Sorry it's been a while - our default ZRC2 proxy contract at https://github.com/Zilliqa/zilliqa-developer/tree/main/contracts/experimental/ERC20ProxyForZRC2 has uint256, so I'm going to close this - please reopen (or open an issue there) if more needs to be done.
