### ISSUE TITLE
[BUG] eth_getTransactionCount() doesn't support pending block number.

### ISSUE THREAD

**Issue by rrw-zilliqa** [Zilliqa/Zilliqa#3929]
As title; this makes it impossible (using some frameworks) to submit more than one txn per block - though in order to fix this properly you need to talk to the same seedpub all the time, which we will attempt to address by enabling session affinity. 

A more principled solution will turn up in a ZIP and then be implemented in ZQ2.

**Comment by chetan-zilliqa** [comment]
Implemented in https://github.com/Zilliqa/Zilliqa/pull/3931 PR.

**Comment by mauromedda** [comment]
shipped on ZQ1 mainnet
