### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by kenken64** [Zilliqa/Zilliqa#44]
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp: In member function ‘void Logger::LogMessage(const char*, const char*)’:
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:107:92: error: ‘put_time’ was not declared in this scope
         logfile << "[TID " << PAD(tid, TID_LEN) << "][" << PAD(put_time(gmtTime, "%H:%M:%S"), TIME_LEN) 
                                                                                            ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:30:59: note: in definition of macro ‘PAD’
 #define PAD(n, len) setw(len) << setfill(' ') << right << n
                                                           ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:112:89: error: ‘put_time’ was not declared in this scope
         cout << "[TID " << PAD(tid, TID_LEN) << "][" << PAD(put_time(gmtTime, "%H:%M:%S"), TIME_LEN) << "][" 
                                                                                         ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:30:59: note: in definition of macro ‘PAD’
 #define PAD(n, len) setw(len) << setfill(' ') << right << n
                                                           ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp: In member function ‘void Logger::LogMessage(const char*, const char*, const char*)’:
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:130:92: error: ‘put_time’ was not declared in this scope
         logfile << "[TID " << PAD(tid, TID_LEN) << "][" << PAD(put_time(gmtTime, "%H:%M:%S"), TIME_LEN)
                                                                                            ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:30:59: note: in definition of macro ‘PAD’
 #define PAD(n, len) setw(len) << setfill(' ') << right << n
                                                           ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:136:89: error: ‘put_time’ was not declared in this scope
         cout << "[TID " << PAD(tid, TID_LEN) << "][" << PAD(put_time(gmtTime, "%H:%M:%S"), TIME_LEN)
                                                                                         ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:30:59: note: in definition of macro ‘PAD’
 #define PAD(n, len) setw(len) << setfill(' ') << right << n
                                                           ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp: In member function ‘void Logger::LogMessageAndPayload(const char*, const std::vector<unsigned char>&, size_t, const char*)’:
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:169:5: error: ‘unique_ptr’ was not declared in this scope
     unique_ptr<char[]> payload_string = make_unique<char[]>(payload_string_len);
     ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:169:16: error: expected primary-expression before ‘char’
     unique_ptr<char[]> payload_string = make_unique<char[]>(payload_string_len);
                ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:172:9: error: ‘payload_string’ was not declared in this scope
         payload_string.get()[payload_string_idx++] = hex_table[(payload.at(payload_idx) >> 4) & 0xF];
         ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:175:5: error: ‘payload_string’ was not declared in this scope
     payload_string.get()[payload_string_len-1] = '\0';
     ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:189:96: error: ‘put_time’ was not declared in this scope
             logfile << "[TID " << PAD(tid, TID_LEN) << "][" << PAD(put_time(gmtTime, "%H:%M:%S"), TIME_LEN)
                                                                                                ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:30:59: note: in definition of macro ‘PAD’
 #define PAD(n, len) setw(len) << setfill(' ') << right << n
                                                           ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:196:96: error: ‘put_time’ was not declared in this scope
             logfile << "[TID " << PAD(tid, TID_LEN) << "][" << PAD(put_time(gmtTime, "%H:%M:%S"), TIME_LEN)
                                                                                                ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:30:59: note: in definition of macro ‘PAD’
 #define PAD(n, len) setw(len) << setfill(' ') << right << n
                                                           ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:205:93: error: ‘put_time’ was not declared in this scope
             cout << "[TID " << PAD(tid, TID_LEN) << "][" << PAD(put_time(gmtTime, "%H:%M:%S"), TIME_LEN)
                                                                                             ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:30:59: note: in definition of macro ‘PAD’
 #define PAD(n, len) setw(len) << setfill(' ') << right << n
                                                           ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:212:93: error: ‘put_time’ was not declared in this scope
             cout << "[TID " << PAD(tid, TID_LEN) << "][" << PAD(put_time(gmtTime, "%H:%M:%S"), TIME_LEN)
                                                                                             ^
/home/kenneth/Projects/Zilliqa/Zilliqa/src/libUtils/Logger.cpp:30:59: note: in definition of macro ‘PAD’
 #define PAD(n, len) setw(len) << setfill(' ') << right << n
                                                           ^
src/libUtils/CMakeFiles/Utils.dir/build.make:86: recipe for target 'src/libUtils/CMakeFiles/Utils.dir/Logger.cpp.o' failed
make[2]: *** [src/libUtils/CMakeFiles/Utils.dir/Logger.cpp.o] Error 1
CMakeFiles/Makefile2:1421: recipe for target 'src/libUtils/CMakeFiles/Utils.dir/all' failed
make[1]: *** [src/libUtils/CMakeFiles/Utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  4%] Building CXX object src/depends/common/CMakeFiles/Common.dir/CommonIO.cpp.o
[  4%] Building CXX object src/depends/libDatabase/CMakeFiles/Overlay.dir/OverlayDB.cpp.o
[  5%] Building CXX object src/depends/json_spirit/CMakeFiles/json_spirit.dir/json_spirit_value.cpp.o
[  6%] Building CXX object src/depends/common/CMakeFiles/Common.dir/FileSystem.cpp.o
[  7%] Building CXX object src/depends/common/CMakeFiles/Common.dir/FixedHash.cpp.o
[  8%] Building CXX object src/depends/json_spirit/CMakeFiles/json_spirit.dir/json_spirit_writer.cpp.o
[  9%] Linking CXX shared library libOverlay.so
[  9%] Built target Overlay
[  9%] Building CXX object src/depends/common/CMakeFiles/Common.dir/RLP.cpp.o
[ 10%] Building CXX object src/depends/common/CMakeFiles/Common.dir/SHA3.cpp.o
[ 10%] Linking CXX shared library libCommon.so
[ 10%] Built target Common
[ 10%] Linking CXX shared library libjson_spirit.so
[ 10%] Built target json_spirit
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bb111189** [comment]
Is it possible to provide more information about your system such as the gcc version and operating system info.

**Comment by kenken64** [comment]
gcc (Ubuntu 4.9.4-2ubuntu1) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

**Comment by kenken64** [comment]
I tried switching it to gcc 6 gottten a different error

CMakeFiles/Test_Sha3.dir/Test_Sha3.cpp.o: In function `SHA256_check_896bitsx3::test_method()':
/home/kenneth/Projects/Zilliqa/tests/Crypto/Test_Sha3.cpp:65: undefined reference to `DataConversion::HexStrToUint8Vec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/kenneth/Projects/Zilliqa/tests/Crypto/Test_Sha3.cpp:72: undefined reference to `DataConversion::HexStrToUint8Vec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Test_Sha3.dir/Test_Sha3.cpp.o: In function `SHA256_check_896bitsx3_updatewithoffset::test_method()':
/home/kenneth/Projects/Zilliqa/tests/Crypto/Test_Sha3.cpp:91: undefined reference to `DataConversion::HexStrToUint8Vec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/kenneth/Projects/Zilliqa/tests/Crypto/Test_Sha3.cpp:98: undefined reference to `DataConversion::HexStrToUint8Vec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Test_Sha3.dir/Test_Sha3.cpp.o: In function `SHA512_check_896bitsx3::test_method()':
/home/kenneth/Projects/Zilliqa/tests/Crypto/Test_Sha3.cpp:117: undefined reference to `DataConversion::HexStrToUint8Vec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Test_Sha3.dir/Test_Sha3.cpp.o:/home/kenneth/Projects/Zilliqa/tests/Crypto/Test_Sha3.cpp:124: more undefined references to `DataConversion::HexStrToUint8Vec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
collect2: error: ld returned 1 exit status
tests/Crypto/CMakeFiles/Test_Sha3.dir/build.make:100: recipe for target 'tests/Crypto/Test_Sha3' failed
make[2]: *** [tests/Crypto/Test_Sha3] Error 1
CMakeFiles/Makefile2:1707: recipe for target 'tests/Crypto/CMakeFiles/Test_Sha3.dir/all' failed
make[1]: *** [tests/Crypto/CMakeFiles/Test_Sha3.dir/all] Error 2

**Comment by kenken64** [comment]
No reply ?

**Comment by adhood** [comment]
Were you ever able to fix this? I get the same error.

**Comment by jiayaoqijia** [comment]
Hi all, 
Right now we only support Ubuntu 16.04 and later we'll try to provide a docker image for you to use. Thanks for your understanding.
