### ISSUE TITLE
Is there anyway to start API server from local machine

### ISSUE THREAD

**Issue by siliconavengers** [Zilliqa/Zilliqa#454]
I'm following the guide to start Zilliqa locally from [README.md](https://github.com/Zilliqa/Zilliqa#running-zilliqa-locally-using-10-shard-nodes-and-ds-node-locally). I would like to run Zilliqa and access API server from local, but I can't. I don't know how to start API server.

I wrote an example by Javascript to access data in local Zilliqa nodes

```javascript
let { Zilliqa } = require('zilliqa.js');

//For local testing, use URL = 'http://localhost:4201'
//To connect to the external network, use URL = 'https://api-scilla.zilliqa.com'

let zilliqa = new Zilliqa({
    nodeUrl: "http://localhost:4201"
    //nodeUrl: "https://api-scilla.zilliqa.com"
});

let node = zilliqa.getNode();

let privateKey = zilliqa.util.generatePrivateKey();
let address = zilliqa.util.getAddressFromPrivateKey(privateKey);

/*
    APIs
*/

zilliqa.node.getNetworkId(function(err, data) {
    if (err || !data.result) {
        console.log(err)
    } else {
        console.log(data.result)
    }
})
```

Can you guys take a look and correct me if I'm wrong

**Comment by bb111189** [comment]
Your system may not have the require resources as it is running 20 nodes at one time. You may try reducing `<MAXMESSAGE>32</MAXMESSAGE>` in https://github.com/Zilliqa/Zilliqa/blob/master/constants_local.xml to 16 or 8.

**Comment by siliconavengers** [comment]
@bb111189 thank you.

Is there anyway to setup sharding on my test instance? For now I can't create a transaction.

When I check the source code I found

```cpp
// from Server.cpp
{
            LOG_GENERAL(INFO, "No shards yet");

            return "Could Not Create Transaction";
}
```

**Comment by bb111189** [comment]
From your logs, I noticed `sudo: unable to resolve host ip-10-20-20-27`. Seems like it is unable to to resolve to some host. 

Can you provide logs from build/local_run and build_lookup/local_run. Maybe just first node log will do.
