### ISSUE TITLE
Enable CI for Linux builds

### ISSUE THREAD

**Issue by sharwell** [Zilliqa/Zilliqa#48]
Enabling a CI early for Linux builds will improve the ability of developers working on other operating systems to confidently submit proposed changes without breaking builds on other platforms. In particular, I would recommend enabling travis-ci for Linux build support prior to merging changes for other operating systems.

If you have any questions about getting this set up, let me know. I've worked with several other projects using travis-ci, including but not limited to ones using C++.

**Comment by bb111189** [comment]
Yes. I will setup the account for Travis-CL soon

**Comment by bb111189** [comment]
Travis-cl enabled.
