### ISSUE TITLE
Allow `amount` to be string in `checkJsonTx`

### ISSUE THREAD

**Issue by iantanwx** [Zilliqa/Zilliqa#524]
Currently, https://github.com/Zilliqa/Zilliqa/blob/master/src/libServer/JSONConversion.cpp#L213 returns `false` if the transaction's `amount` field is not an integer. This is a problem for the client side library, as JS's maximum safe integer size is 53 bits. Normally, this should not be a problem; however, Amrit ran into this a week or so ago. As a result, `amount` should be parsed as a string and cast to a `BN` on the C++ side, since it also cannot be guaranteed that a 64 bit integer will not overflow.

cc @bb111189

**Comment by AmritKumar** [comment]
`amount` will requin sred around 70 bits, so I think we are using 128 bits internally.

**Comment by KaustubhShamshery** [comment]
https://github.com/Zilliqa/Zilliqa/tree/fix/ServerAmount

Merging of this branch should be coupled with the change in front end.
Also, should we do the same for the nonce, it is also an number as of now.

**Comment by iantanwx** [comment]
It would take a lot of transactions to hit the limit, but I suppose we might as well do this since it doesn’t cost a lot. @AmritKumar what are your thoughts?

**Comment by iantanwx** [comment]
This has been fixed a Long time ago.
