### ISSUE TITLE
API Feature Request - Transaction Filtering

### ISSUE THREAD

**Issue by taoteh1221** [Zilliqa/Zilliqa#538]
I'm proposing / requesting a new API for the Zilliqa network, for filtering transactions, similar to what Parity has for Ethereum's chain. Please see below Parity API example:
```
curl --data '{"method":"trace_filter","params":[{"fromBlock":"0x2ed0c4","toBlock":"0x2ed128","toAddress":["0x8bbB73BCB5d553B5A556358d27625323Fd781D37"]}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

```
Reason being is I'm not seeing any APIs like this at https://apidocs.zilliqa.com . I'm building a block explorer app, and as you can see on this address example page, I have not come up with an easy solution to retrieving an address's transaction history yet: https://zillexplorer.io/address/0xbf5fce968f014f30e7aca95098689fd644d814b1 . I'll be caching / refreshing transaction data (with a corresponding hash to verify it) in a normal db after initial retrieval, for latency's sake. 

@AmritKumar suggested parsing through each block manually for now, but I'm unfamiliar with Zilliqa's native application binary as a) I'd need to be whitelisted to join the testnet currently, and b) I'm unaware of any CLI documentation being publicly available yet?

For reference if it helps, my project's github repo is here: https://github.com/taoteh1221/Zillexplorer

**Comment by taoteh1221** [comment]
I just noticed it seems you are planning on implementing "GetTransactionHistory" here: https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/master/src/node.ts#L191

fromBlock / toBlock like parity uses could prove useful too, especially if one already has the transaction history up to a certain point in a legacy db.

**Comment by Gnnng** [comment]
Hey @taoteh1221, thanks for reaching out to us. It's now on our to-do list. We will let you know when it's done.

**Comment by taoteh1221** [comment]
Hello @Gnnng. You're welcome, thanks for scheduling this in to implement. I appreciate it.

**Comment by deepgully** [comment]
+1 
I need this feature to retrieve transactions by from/to address.
