### ISSUE TITLE
Compilation fails on MACOS High Sierra

### ISSUE THREAD

**Issue by vinayjt** [Zilliqa/Zilliqa#541]
Node.cpp:497:24: error: no matching constructor for initialization of 'PrivKey'
        auto privKey = PrivKey{privKeyBytes, 0};

Looks auto is not resolving to correct data type. for privKeyBytes.

**Comment by vinayjt** [comment]
it worked after changing auto to specific type   const vector<unsigned char>

**Comment by Gnnng** [comment]
Hi @vinayjt Can you share more information with us? Anything that can help us to reproduce this would be helpful. Thanks

**Comment by vinayjt** [comment]
Hi Gong,

Nothing was changed in master branch, so it should be happening if you
compile master branch on MAC OS. Not sure why it would compile otherwise.

On MAC-OS  the clang compiler I have .
Code at ~line 388 in file src/libNode/Node.cpp is resolving  to
'std::initializer_list<std::__1::vector<unsigned
char, std::__1::allocator<unsigned char> > >
     auto privKeyBytes{DataConversion::HexStrToUint8Vec(privKeyHexStr)};
which I think is correct.
and
because of that next line is failing find the constructor .

 auto privKey = PrivKey(privKeyBytes, 0);


I think the solution is either class PrivKey provides std::initializer_list
constructor or change the auto to specific type , at line 388.


Regards,
Vinay

**Comment by Gnnng** [comment]
Hi @vinayjt, we actually do run the build for macOS on Travis (10.3.3 High Sierra) regularly or on some core devs' Macbook (10.3.5 High Sierra). And the compiler we used is the default clang installed in the system. See the travis log [here](https://travis-ci.com/Zilliqa/Zilliqa/jobs/142568881#L243-L254) from a master branch build on macOS or the output from a macbook build as follows.

```console
$ ./build.sh
-- Found ccache
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```

Perhaps, the compiler version could be the issue. Hope this information could be helpful.
