### ISSUE TITLE
API Feature Request - Get Contract Address By Transaction ID

### ISSUE THREAD

**Issue by neeboo** [Zilliqa/Zilliqa#574]
**Description**:

The Contract Address is created when `CreateTransaction` is done.  After deploying a SmartContract using `CreateTransaction` API, it returns TransactionID as the result.
However, we don't know if it the SmartContract is deployed currently, unless we do one more call to `GetContracts` using Account Address which previously deployed/invoked the contract. After that,  we get list of the contract, but we still have to 'guess' which one of the result is the correct one.

So I hope if the contract address is returned by CreateTransaction API. It would be much better.

Example:

```
curl -d '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "CreateTransaction",
    "params": [{
      "version": 0,
      "nonce": 5,
      "to": "c5a829596fb06a59e2b1ddb6589811c759025d52",
      "amount": 83,
      "pubKey": "026ad7a7cb2aa230af177ca0ea3c4112a902d296bf7a5f25f5ae4b3df72321f4d0",
      "gasPrice": 1,
      "gasLimit": 1,
      "signature": "508b838641a6d0f9a7114c5b359a3a6119072e213b06b0f3331f4a33a8c80cde09d3aa7f64c3d767024ab56abbcb2ebd553085d214133c0383d4007828bde0c4"
    }]
}' -H "Content-Type: application/json" -X POST "https://api-scilla.zilliqa.com/"
```

The above command returns JSON structured like this:
```

{
  "id": "1",
  "jsonrpc": "2.0",
  "result":{
     "txnId":"a5e238bca907c28d015e50acc76788f8bad79882bf40459215722c414a7b940b",
     "contractAddr:"sssssssssssssssssssssssssssssssssssssssss"
  }
}
// result should be normalized as Objects,
// with "txnId" and "contractAddress" as their keys.
```

**Furthermore**:
Because transaction and contract are related in a way. What if we consider using TransactionID as parameter to request, and get the correct Contract Address?

like this:

```
curl -d '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetContractAddressByTransaction",
    "params": ["43104643E5F35455B71F3CFCB471CE4A4C8B96E00F8E8B77733075662E5FC905"]
}' -H "Content-Type: application/json" -X POST "https://api-scilla.zilliqa.com/"

```
The above command returns JSON structured like this:

```
{
  "id": "1",
  "jsonrpc": "2.0",
  "result": {contractAddr:'sssssssssssssssssssssssssssssssssssssssss'}
}
```

The APIs should be added to `zilliqa-js` as well.

**Comment by jiayaoqijia** [comment]
Hi @neeboo , thanks for your feedback. We'll try to support the features soon.

**Comment by iantanwx** [comment]
@neeboo I'm going to close this issue, as #675 and #587 in conjunction with https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/feature/monorepo/packages/zilliqa-js-contract/src/index.ts have effectively solved this issue for client developers.
