### ISSUE TITLE
Improve shard size calculator test

### ISSUE THREAD

**Issue by ansnunez** [Zilliqa/Zilliqa#577]
Re-write the test to be more exhaustive by looping over the range and trying each value (less one, equal, and plus one). For example, 0/1 for range value 0, 650/651/652 for range value 651, ... I think this can be done with a single for loop in one test function only.

Reference: discussion in PR #572

**Comment by Gnnng** [comment]
Seems @bb111189 removed those assert lines in https://github.com/Zilliqa/Zilliqa/pull/572/commits/f94ff0e14079b6bd3d04daf61ee5ab397fd3f04c. Perhaps it's too late to bring them back as the PR is ready to merge. Maybe we can have them when we resolve this issue. 

The assert would work nicely with the unit testing code (debug build) and have no impact in production (release build)

**Comment by ansnunez** [comment]
Test improved in #764
