### ISSUE TITLE
build.sh Error!

### ISSUE THREAD

**Issue by zhanghuahua0708** [Zilliqa/Zilliqa#665]
../../src/libServer/libServer.a(Server.cpp.o): In function `Server::GetRecentTransactions()':
/work/Zilliqa/src/libServer/Server.cpp:931: undefined reference to `Json::Value::append(Json::Value&&)'
../../src/libServer/libServer.a(Server.cpp.o): In function `Server::GetShardingStructure()':
/work/Zilliqa/src/libServer/Server.cpp:956: undefined reference to `Json::Value::append(Json::Value&&)'
../../src/libServer/libServer.a(JSONConversion.cpp.o): In function `JSONConversion::convertBoolArraytoJson(std::vector<bool, std::allocator<bool> > const&)':
/work/Zilliqa/src/libServer/JSONConversion.cpp:43: undefined reference to `Json::Value::append(Json::Value&&)'
../../src/libServer/libServer.a(JSONConversion.cpp.o): In function `JSONConversion::convertTxnHashArraytoJson(std::vector<dev::FixedHash<32u>, std::allocator<dev::FixedHash<32u> > > const&)':
/work/Zilliqa/src/libServer/JSONConversion.cpp:53: undefined reference to `Json::Value::append(Json::Value&&)'
../../src/libServer/libServer.a(JSONConversion.cpp.o): In function `JSONConversion::convertTxnHashArraytoJson(std::vector<MicroBlockHashSet, std::allocator<MicroBlockHashSet> > const&)':
/work/Zilliqa/src/libServer/JSONConversion.cpp:63: undefined reference to `Json::Value::append(Json::Value&&)'
collect2: error: ld returned 1 exit status
tests/POW/CMakeFiles/Test_POW.dir/build.make:141: recipe for target 'tests/POW/Test_POW' failed
make[2]: *** [tests/POW/Test_POW] Error 1

I already install the dependencies but still exe build.sh wrong! Who can tell me how to fix it if you know this error.

**Comment by ShengguangXiao** [comment]
@zhanghuahua0708 What OS are you using?

**Comment by zhanghuahua0708** [comment]
ubuntu16, it's ok after I try to do it  again and again, thanks!
------------------------------------------------------------------
发件人：Xiao Shengguang <notifications@github.com>
发送时间：2018年10月9日(星期二) 15:53
收件人：Zilliqa/Zilliqa <Zilliqa@noreply.github.com>
抄　送：jarven <whuaw@aliyun.com>; Mention <mention@noreply.github.com>
主　题：Re: [Zilliqa/Zilliqa] build.sh Error! (#665)

@zhanghuahua0708 What OS are you using?

**Comment by jiayaoqijia** [comment]
Fixed.
