### ISSUE TITLE
How to mining in the public testnet?

### ISSUE THREAD

**Issue by zhanghuahua0708** [Zilliqa/Zilliqa#678]
I want to mining in the public testnet, but I don't know how to connect the testnet ,  I just run the test_node_simple.sh. AnyBody knows that?

**Comment by jiayaoqijia** [comment]
Hi @zhanghuahua0708 , thanks for your interest. Right now, you can start to mine in the local testnet using you GPU devices. Later, we'll open our testnet to the public and provide instructions for community members to mine test tokens. Thanks.
