### ISSUE TITLE
How to get the balance of my local account?

### ISSUE THREAD

**Issue by zhanghuahua0708** [Zilliqa/Zilliqa#682]
I execute the cmd "./tests/Node/test_node_simple.sh" to mining in local , but, I don't know whether I have mined a new block, what my account address  is, and what the balance of my account is.....

**Comment by iantanwx** [comment]
You have to call the RPC method `GetBalance`, and pass your address.

**Comment by zhanghuahua0708** [comment]
I don't know how to get my address, there isn't RPC method to create it @iantanwx

**Comment by evesnow91** [comment]
Outdated issue.
