### ISSUE TITLE
libServer Improvements

### ISSUE THREAD

**Issue by ansnunez** [Zilliqa/Zilliqa#718]
These are some of the comments to address in ongoing work on libServer:
1. See if we are using the `try`-`catch` correctly.  One use is for hex-to-byte conversions, to avoid crashing.
2. See if txn block count variables can be reduced from `uint256_t` to `uint64_t`.
3. See if it's possible to implement a filter for `ContractState`, to avoid passing the entire contract state over the network each time a client polls the look up node.

**Comment by bb111189** [comment]
@KaustubhShamshery Can you take a look to see whether this issue is still relevant or not?

**Comment by KaustubhShamshery** [comment]
only the 3 seems relevant

**Comment by iantanwx** [comment]
I think we can close this. These have already been addressed one way or the other, and bloom filters should have their own issue.

**Comment by ansnunez** [comment]
Ok agreed
