### ISSUE TITLE
OSX ./build.sh Can't Find Boost, Configuring incomplete, errors occurred! 

### ISSUE THREAD

**Issue by Speccles96** [Zilliqa/Zilliqa#720]
Last login: Mon Oct 22 01:30:47 on ttys003
Davids-MacBook-Pro:Zilliqa david$ ./build.sh opencl
Build with OpenCL
-- We are on a Darwin system
-- Building and installing g3log
-- Building and installing mongo driver. This could take longer
CMake Warning at /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:30 (find_package)

CMake Warning at /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:30 (find_package)

CMake Warning at /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:30 (find_package)

-- Could NOT find Boost
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.8.4
-- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.dylib (found version "1.0.2p")  
-- Found leveldb: /usr/local/lib/libleveldb.dylib  
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework (found version "1.2") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found version "3.6.1") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common
   used as include directory in directory /Users/david/Zilliqa/src/depends/common

-- Configuring incomplete, errors occurred!
See also "/Users/david/Zilliqa/build/CMakeFiles/CMakeOutput.log".
See also "/Users/david/Zilliqa/build/CMakeFiles/CMakeError.log"

**Comment by bb111189** [comment]
Closing this issue as it is obsoleted. Please reopen this issue or post it at https://forum.zilliqa.com/ if you are still facing any issue.
