### ISSUE TITLE
Add compiler version check inside CMakefile

### ISSUE THREAD

**Issue by ansnunez** [Zilliqa/Zilliqa#744]

**Comment by ckyang** [comment]
ckyang@ckyang-Latitude-7480:~/Git/Zilliqa$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

Build failed:

[ 70%] Building CXX object src/libProtoServer/CMakeFiles/ProtoServer.dir/ServerRequest.pb.cc.o
ServerRequest.pb.cc: In member function ‘virtual google::protobuf::uint8* ZilliqaMessage::GetStorageAtRequest::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
ServerRequest.pb.cc:362:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
    bool deterministic, ::google::protobuf::uint8* target) const {
         ^~~~~~~~~~~~~
ServerRequest.pb.cc: In member function ‘virtual google::protobuf::uint8* ZilliqaMessage::GetBlockTransactionCountRequest::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
ServerRequest.pb.cc:760:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
    bool deterministic, ::google::protobuf::uint8* target) const {
         ^~~~~~~~~~~~~
ServerRequest.pb.cc: In member function ‘virtual google::protobuf::uint8* ZilliqaMessage::CreateTransactionRequest::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
ServerRequest.pb.cc:1071:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
    bool deterministic, ::google::protobuf::uint8* target) const {
         ^~~~~~~~~~~~~
ServerRequest.pb.cc: In member function ‘virtual google::protobuf::uint8* ZilliqaMessage::GetTransactionRequest::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
ServerRequest.pb.cc:1378:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
    bool deterministic, ::google::protobuf::uint8* target) const {
         ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
src/libProtoServer/CMakeFiles/ProtoServer.dir/build.make:86: recipe for target 'src/libProtoServer/CMakeFiles/ProtoServer.dir/ServerRequest.pb.cc.o' failed
make[2]: *** [src/libProtoServer/CMakeFiles/ProtoServer.dir/ServerRequest.pb.cc.o] Error 1
CMakeFiles/Makefile2:1839: recipe for target 'src/libProtoServer/CMakeFiles/ProtoServer.dir/all' failed
make[1]: *** [src/libProtoServer/CMakeFiles/ProtoServer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by Gnnng** [comment]
We can close it now as the issue mentioned has been fixed and our code can be built on Ubuntu 18.04.
