### ISSUE TITLE
Zilliqa crushes with many @@@@@@ in log file

### ISSUE THREAD

**Issue by un1t** [Zilliqa/Zilliqa#997]
I use native miner (cuda 10) on Ubuntu 16.04 built with this instruction https://github.com/Zilliqa/Zilliqa/wiki/Mining

Miner crushes after a while with many @@@@@@@ in log file.

> [INFO   ][ 3107][22:30:02:335][SendMessageToLookupNodesSerial] END
> [INFO   ][ 3107][22:30:02:335][GetOfflineLookupNodes         ] END
> [WARNING][ 1020][22:30:02:460][RumorReceived                 ] Round is not running. Ignoring message!!
> ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@

Full log attached
[zilliqa-00001-log.txt.gz](https://github.com/Zilliqa/Zilliqa/files/2646882/zilliqa-00001-log.txt.gz)

**Comment by un1t** [comment]
Oh, I just found out that there is private key in log. So if it would be mainnet I would lost my coins.
Do you really need to put private key in log?
And also please add current date in log, without it it is hard to say what exactly day it was when something was logged.

**Comment by jiayaoqijia** [comment]
> Oh, I just found out that there is private key in log. So if it would be mainnet I would lost my coins.
> Do you really need to put private key in log?
> And also please add current date in log, without it it is hard to say what exactly day it was when something was logged.

Thanks for your feedback. We've removed the relevant log information in the local log file at #1011 . We'll also provide the date in the log as well soon.  Thanks.

**Comment by evesnow91** [comment]
Issue resolved.
